ci/script.sh
docker/mips-unknown-linux-gnu/Dockerfile
docker/mips64-unknown-linux-gnuabi64/Dockerfile
docker/override.sh
docker/powerpc64-unknown-linux-gnu/Dockerfile

to include alexcrichton/curl-rust#137
But only for the targets affected by #4
closes #4

override the curl-sys crate

---

CHANGELOG.md
src/cargo.rs
src/docker.rs
src/extensions.rs
src/file.rs
src/main.rs
src/rustc.rs
src/rustup.rs

print shell commands when the verbose flag is used

---

ci/script.sh
docker/thumbv6m-none-eabi/Dockerfile

- gcc + libc6-dev to be able to build build scripts
- libnewlib-dev to be able to cross compile C code for these targets

install more packages on the thumb*-none-eabi* images

---

CHANGELOG.md
README.md
ci/script.sh
src/docker.rs

generate lockfile when necessary

---

.travis.yml
README.md
ci/script.sh
docker/mips-unknown-linux-gnu/Dockerfile
docker/powerpc64-unknown-linux-gnu/Dockerfile
docker/x86_64-pc-windows-gnu/Dockerfile
src/main.rs

add support for x86_64-pc-windows-gnu

---

.travis.yml
Cargo.lock
README.md
ci/script.sh
docker/aarch64-linux-android/Dockerfile
docker/android-ndk.sh
docker/arm-linux-androideabi/Dockerfile
docker/armv7-linux-androideabi/Dockerfile
docker/i686-linux-android/Dockerfile
src/main.rs

Fixes https://github.com/japaric/cross/issues/80

Add android build support

---

README.md
docker/aarch64-linux-android/Dockerfile
docker/aarch64-unknown-linux-gnu/Dockerfile
docker/arm-linux-androideabi/Dockerfile
docker/arm-unknown-linux-gnueabi/Dockerfile
docker/armv7-linux-androideabi/Dockerfile
docker/armv7-unknown-linux-gnueabihf/Dockerfile
docker/i686-linux-android/Dockerfile
docker/i686-unknown-freebsd/Dockerfile
docker/i686-unknown-linux-gnu/Dockerfile
docker/mips-unknown-linux-gnu/Dockerfile
docker/mips64-unknown-linux-gnuabi64/Dockerfile
docker/mips64el-unknown-linux-gnuabi64/Dockerfile
docker/mipsel-unknown-linux-gnu/Dockerfile
docker/openssl.sh
docker/powerpc-unknown-linux-gnu/Dockerfile
docker/powerpc64-unknown-linux-gnu/Dockerfile
docker/powerpc64le-unknown-linux-gnu/Dockerfile
docker/s390x-unknown-linux-gnu/Dockerfile
docker/sparc64-unknown-linux-gnu/Dockerfile
docker/x86_64-unknown-dragonfly/Dockerfile
docker/x86_64-unknown-freebsd/Dockerfile
docker/x86_64-unknown-linux-gnu/Dockerfile
docker/x86_64-unknown-linux-musl/Dockerfile
docker/x86_64-unknown-netbsd/Dockerfile

bump openssl to 1.0.2k

---

README.md

Fix binfmt_misc link

---

docker/aarch64-unknown-linux-gnu/Dockerfile
docker/arm-unknown-linux-gnueabi/Dockerfile
docker/arm-unknown-linux-musleabi/Dockerfile
docker/armv7-unknown-linux-gnueabihf/Dockerfile
docker/armv7-unknown-linux-musleabihf/Dockerfile
docker/mips-unknown-linux-gnu/Dockerfile
docker/mips64-unknown-linux-gnuabi64/Dockerfile
docker/mips64el-unknown-linux-gnuabi64/Dockerfile
docker/mipsel-unknown-linux-gnu/Dockerfile
docker/powerpc-unknown-linux-gnu/Dockerfile
docker/powerpc64-unknown-linux-gnu/Dockerfile
docker/powerpc64le-unknown-linux-gnu/Dockerfile
docker/qemu.sh
docker/s390x-unknown-linux-gnu/Dockerfile
docker/sparc64-unknown-linux-gnu/Dockerfile
docker/thumbv6m-none-eabi/Dockerfile
docker/thumbv7em-none-eabi/Dockerfile
docker/thumbv7em-none-eabihf/Dockerfile
docker/thumbv7m-none-eabi/Dockerfile

this should fix the powerpc failures

bump qemu version to 2.9.0

---

docker/musl.sh

musl: fix type in ./configure invocation

---

.travis.yml

add the x86_64-linux target to CI for real

---

docker/sparc64-unknown-linux-gnu/Dockerfile

fix the sparc64 linker

---

.travis.yml
Cargo.lock
README.md
docker/openssl.sh

upgrade OpenSSL to 1.0.2m

---

docker/armv7-unknown-linux-gnueabihf/Dockerfile
docker/i686-unknown-linux-gnu/Dockerfile
docker/x86_64-unknown-linux-gnu/Dockerfile

12.04 reached end of life in April 2017

Update to 14.04 LTS.

---

docker/armv7-unknown-linux-gnueabihf/Dockerfile
docker/i686-unknown-linux-gnu/Dockerfile
docker/x86_64-unknown-linux-gnu/Dockerfile

Revert "Update to 14.04 LTS."

---

README.md

add travis to readme

---

.travis.yml
build-docker-image.sh
ci/deploy.sh

Apparently, the deploy script has to be invoked as a script instead of inline Bash.

Fix Travis deployment again.

---

ci/before_deploy.sh

Only build the release artifact when `DEPLOY` is set to 1.

Fix `before_deploy.sh`.

---

src/config.rs
src/docker.rs
src/errors.rs
src/main.rs
src/rustc.rs

#147 
Config is the facade and gets first from env then from toml.
All references to toml change to config.
What are your thoughts?
---
Closes https://github.com/rust-embedded/cross/pull/460.

Allow config settings with environment variables

---

src/docker.rs

remove extra slash

---

CHANGELOG.md
Cargo.toml
src/config.rs
src/docker.rs
src/main.rs
src/rustup.rs

also removes author field as it is not displayed on crates.io anymore.

change edition to 2021

---

docker/qemu.sh

in preparation of potential aarch64 host support

update config.guess in centos builds

---

.github/ISSUE_TEMPLATE/a_blank_issue.md
.github/ISSUE_TEMPLATE/b_issue_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/z_feature_request.yml

add issue templates

---

src/bin/cross-util.rs

Previously, our extraction using `rustembedded_target` could fail if there was a character that did not match `\w` in our triple. This failed with targets like `thumbv8m.main-none-eabi`, and therefore should be considered just as a precaution.

Fix target extraction from `rustembedded` images.

---

src/docker.rs

Store the path to the engine in a variable, so we can limit the number of calls to `get_container_engine` so we can only use it once, avoiding using multiple commands per docker command.
This is relevant for docker remote support, where we might make 20+ docker commands. Here, since we only make 2, it's much less relevant but still good practice.

Limit calls to which to find container engine path.

---

xtask/src/hooks.rs
xtask/src/main.rs
xtask/src/pre-commit.sh
xtask/src/pre-push.sh

Convert git hooks to use `xtask` commands, and add `shellcheck` to `xtask check`. Can run on staged or all files.

Add shellcheck to git hooks and convert to xtask.

---

src/bin/commands/images.rs

Does nothing if there are no images to remove, and now correctly lists the old rustembedded images.

Bug fixes for listing/removing images.

---

xtask/src/build_docker_image.rs

Add build arguments to build-docker-image.

---

src/bin/commands/images.rs

Allows multiple or no targets to be provided to `cross-util images list`, and with a single target, lists all images, while with multiple targets creates a formatted table.
For example:
```bash
$ target/debug/cross-util images list aarch64-pc-windows-msvc
ghcr.io/cross-rs/aarch64-pc-windows-msvc:local
$ target/debug/cross-util images list aarch64-pc-windows-msvc x86_64-apple-darwin
| Targets                 | Images                                         |
|-------------------------|------------------------------------------------|
| aarch64-pc-windows-msvc | ghcr.io/cross-rs/aarch64-pc-windows-msvc:local |
| x86_64-apple-darwin     | ghcr.io/cross-rs/x86_64-apple-darwin:local     |
```
The targets are sorted alphabetically for improved readability.

Formatting and bug fixes for listing images.

---

Cargo.lock
Cargo.toml

release version 0.2.2-rc.1

---

CHANGELOG.md
Cargo.lock
Cargo.toml

release v0.2.2

---

CHANGELOG.md
src/docker/shared.rs

Bug fix for mounted paths for docker-in-docker.

---

CHANGELOG.md
Cargo.lock
Cargo.toml

release version 0.2.4

---

.changes/939.json
src/docker/local.rs
src/docker/remote.rs
src/docker/shared.rs

Fix cross when using absolute paths to the current project.

---

.changes/945.json
src/docker/custom.rs

Fix pre-build Docker image names with Podman.

---

.github/workflows/ci.yml

Update macOS CI version.

---

ci/test-bisect.sh

Works around https://github.com/rust-lang/cargo-bisect-rustc/issues/186.

Fix cargo-bisect-rustc issues during CI.

---

.changes/1006.json
.github/workflows/ci.yml
README.md
docker/Dockerfile.aarch64-unknown-linux-gnu.centos
docker/aarch64-linux-gnu-glibc.sh
src/docker/provided_images.rs

Add Dockerfile.aarch64-unknown-linux-gnu.centos for centos7, using glibc-2.17

Add CentOS7-compatible target for aarch64

---

src/bin/commands/containers.rs
src/bin/commands/images.rs
src/bin/cross-util.rs
src/build.rs
src/cargo.rs
src/docker/custom.rs
src/docker/image.rs
src/docker/local.rs
src/docker/remote.rs
src/docker/shared.rs
src/file.rs
src/lib.rs
src/rustc.rs
src/rustup.rs
xtask/src/build_docker_image.rs
xtask/src/ci.rs
xtask/src/hooks.rs
xtask/src/target_info.rs

volume improvements

---

xtask/src/util.rs

Fix parsing of image targets for building docker images so it only uses subs containing only ASCII letters, so targets like `thumbv8m.main-none-eabihf` aren't mistaken for a target/sub combination.
Closes #1020.

Support docker images with targets containing `.`s.

---

.github/workflows/ci.yml
Cargo.lock
src/docker/provided_images.rs
targets.toml
xtask/Cargo.toml
xtask/src/build_docker_image.rs
xtask/src/ci.rs
xtask/src/ci/target_matrix.rs
xtask/src/codegen.rs
xtask/src/util.rs

Allows for more fine grained try control
```
> bors try --target x86_64*linux* --cpp false
>> Building x86_64-unknown-linux-musl
```
```
OPTIONS:
--cpp <CPP>               [possible values: true, false]
--dylib <DYLIB>           [possible values: true, false]
-h, --help                    Print help information
-r, --runners <RUNNERS>...    
--run <RUN>               [possible values: true, false]
--std <STD>               [possible values: true, false]
-t, --target <TARGET>...      
```

convert and improve matrix generation with a xtask script

---

src/errors.rs

Updates the comment documentation for the async-signal safety guarantees in stopping a running container.

Document remote container termination safety guarantees.

---

.github/workflows/ci.yml
xtask/src/ci/target_matrix.rs

Ensure successful CI conclusion with empty matrix.

---

xtask/src/build_docker_image.rs

useful for passing `--network=host`

add `CROSS_BUILD_OPTS` and `--build-opts` to enable passing more flags

---

.changes/1084.json
src/bin/commands/containers.rs
src/docker/remote.rs

Fix remote docker paths on Windows hosts.

---

.editorconfig
.github/ISSUE_TEMPLATE/b_issue_report.yml
.github/ISSUE_TEMPLATE/z_feature_request.yml
ci/build_release.sh
ci/shared.sh
ci/test.sh
docker/Dockerfile.aarch64-unknown-linux-gnu.centos
docker/aarch64-linux-gnu-glibc.sh
docker/android-ndk.sh
docker/dragonfly.sh
docker/dropbear.sh
docker/freebsd.sh
docker/linux-image.sh
docker/mingw.sh
docker/musl.sh
docker/netbsd.sh
docker/qemu.sh
docker/solaris.sh
xtask/src/target_info.sh

Add editorconfig file.

---

.github/workflows/ci.yml
xtask/src/ci/target_matrix.rs
xtask/src/util.rs

Co-authored-by: Emil Gardström <emil.gardstrom@gmail.com>

Allow CI without requiring targets to be built/tested.

---

.changes/880-1111.json
.changes/880.json
ci/test-zig-image.sh
docker/zig.sh

Update zig-cc and zigbuild versions.

---

README.md

Update documentation on environment variable passthrough.

---

src/docker/build.rs
src/docker/custom.rs
src/docker/mod.rs
xtask/src/build_docker_image.rs
xtask/src/main.rs

Add progress config options to custom image builds.

---

.changes/1049-1142.json
src/cli.rs
src/lib.rs

Ensure ignored CLI arguments to cross are always passed at the end.

---

.gitattributes
docker/.gitattributes

be more explicit about eol

---

.changes/1164.json
docker/freebsd-common.sh
docker/freebsd-extras.sh
docker/freebsd-install.sh
docker/freebsd.sh

Add package site mirrors for FreeBSD.

---

.changes/1038-1220.json
.changes/1038.json
.changes/1220.json
.github/workflows/ci.yml
Cargo.lock
Cargo.toml
README.md
clippy.toml
deny.toml
src/cross_toml.rs
src/docker/mod.rs
src/docker/remote.rs
src/docker/shared.rs
src/file.rs
src/lib.rs
src/rustup.rs
src/shell.rs
xtask/Cargo.toml
xtask/src/changelog.rs
xtask/src/util.rs

don't pass in `--target-dir` when it's not needed

---

src/lib.rs
src/rustc.rs
src/rustup.rs

also fixes suggestion when using wrong channel
resolves #1192

suggest reinstalling the toolchain

---

.changes/1265.json
Cargo.lock
Cargo.toml
src/errors.rs

use signal-hook instead of ctrlc

---

.github/workflows/ci.yml
xtask/src/ci.rs
xtask/src/ci/target_matrix.rs

this pr implements part of #1249
We now use merge queues, which work in a similar way, except there is no batching of prs.

rip bors - switch to merge queues

---

.github/workflows/ci.yml

fix build in merge queue

---

.changes/1373.json
docker/windows-entry.sh

partially fix for #1372 and fixes #1371

don't fail when wineboot fails

---

.github/workflows/weekly.yml

fix weekly check

---

.changes/1159.json
Cargo.toml
src/bin/commands/run.rs
src/cargo.rs
src/config.rs
src/cross_toml.rs
src/lib.rs
src/tests/toml.rs

some minor refactoring and parse `[workspace.metadata.cross]`
fixes #1158

metadata config

---

.github/workflows/ci.yml
xtask/src/ci/target_matrix.rs

fixes issue introduced in #1431

improve tests

---

docker/zig.sh

Bump zigbuild version
Fix #1479

fix: zig cc unknown operating system

---

.changes/1374-1490.json
docker/wine.sh

fixes missing bcryptprimitives dep

bump wine to 9

---

.github/actions/cargo-install-upload-artifacts/action.yml
.github/actions/cargo-publish/action.yml
.github/workflows/ci.yml
docker/Dockerfile.aarch64-unknown-linux-gnu.centos
docker/Dockerfile.native.centos
docker/linux-image.sh

- fix centos
- bump kernel
- fix ci

fix linux images
