cross-rs/cross

- docker/thumbv6m-none-eabi/Dockerfile
- docker/thumbv7em-none-eabi/Dockerfile
- docker/thumbv7em-none-eabihf/Dockerfile
- docker/thumbv7m-none-eabi/Dockerfile
Adds `libc.a`, `libm.a`, `crt0.o` and more.
This adds 73.17 MB to the image however.
> add `libnewlib-arm-none-eabi` dep to thumb* targets.

- src/docker.rs
This allows offline work, as `cargo fetch` only updates the lockfile if
necessary, whereas `cargo generate-lockfile` basically does a remove and
regenerate.
> Use `cargo fetch` instead of `cargo generate-lockfile`

- Cargo.lock
- Cargo.toml
- src/docker.rs
- src/main.rs
Fixes #90 
Please let me know if this approach is not satisfactory.
- I added two new dependencies
- I am not sure how we can test this
> Fixes permission issues with userns on Docker host

- .travis.yml
- README.md
- ci/script.sh
- docker/asmjs-unknown-emscripten/Dockerfile
- docker/emscripten-entry.sh
- docker/emscripten.sh
- docker/node-wasm
- docker/node.sh
- docker/wasm32-unknown-emscripten/Dockerfile
- src/main.rs
Emscripten 1.37.13 provides pre-build binaries, so we do not need to build it. 
Node 8.0.0 can exec wasm files, so we can have test support for both asmjs and wasm32. We use a workaround for https://github.com/kripken/emscripten/issues/4542.
> Add support for emscripten targets

- README.md
- src/docker.rs
- src/main.rs
This adapts @dflemstr's work in #77, removing the `whitelist_all` functionality as requested in review.
fixes #76 
closes #77
> Allow passing through environment variables

- .travis.yml
- docker/emscripten-entry.sh
- docker/emscripten.sh
Fixes https://github.com/japaric/cross/issues/110
> Fix emscripten permission issue

- ci/script.sh
otherwise we run into linking errors (due to multiple codegen units?)
> compile compiler-builtins test suite with the "mangled-names" feature enabled

- src/cargo.rs
This commit adds possibility to
use 'cargo deb' to build debian
packages in Docker image.
cargo-deb project:
https://github.com/mmstick/cargo-deb
> Add subcommand 'deb'

- .travis.yml
- docker/i686-unknown-linux-musl/Dockerfile
Changing the base image of `i686-unknown-linux-musl` from `ubuntu/16.04`
to `i386/ubuntu:16.04` allows us to compile OpenSSL using musl. The
image is based on a 32bit Ubuntu kernel.
Fixes #27
Not entirely sure what else needs to change for the build process, for now I've added the OPENSSL env var to the build matrix. Should be good?
> Support OpenSSL on i686 musl

- README.md
Forgot to update the README with support for OpenSSL on the `i686-unknown-linux-musl` target in PR #27 .
> Update README for i686 musl OpenSSL support

- .travis.yml
- README.md
- docker/solaris.sh
- docker/sparcv9-sun-solaris/Dockerfile
- docker/x86_64-sun-solaris/Dockerfile
- src/main.rs
> Add Solaris targets

- .travis.yml
- README.md
- docker/aarch64-linux-android/Dockerfile
- docker/android-system.sh
- docker/arm-linux-androideabi/Dockerfile
- docker/armv7-linux-androideabi/Dockerfile
- docker/i686-linux-android/Dockerfile
- docker/qemu.sh
- docker/x86_64-linux-android/Dockerfile
We could provide android test support by launching an android emulator and running tests in the emulator (like how it is done in libc and rust), but there is licenses issues in redistributing the sdk (see 3.4 of https://developer.android.com/studio/terms.html). Off course, I maybe be wrong about this.
So we download and build bionic libc from source, which I think allows we to distribute the binaries. Having the android libc allows running native binaries using qemu, which can be enough for projects like, nix, ripgrep, etc.
Related https://github.com/japaric/cross/issues/82
> Add limited android test support

- docker/solaris.sh
- docker/sparcv9-sun-solaris/Dockerfile
- docker/x86_64-sun-solaris/Dockerfile
This changes the solaris2.11 part of the gcc triplet
to solaris2.10, because there is a compatibility issue:
If a rust program panics on Solaris 10 the backtrace
cannot be generated because of a runtime error.
Changing the triplet works for both Solaris 10 and 11.
It is also the same triplet that is used by Rust's CI.
> Use Solaris 10 compatible compiler triplet

- .travis.yml
- CHANGELOG.md
- README.md
- docker/i586-unknown-linux-gnu/Dockerfile
- src/main.rs
> add support for i586-unknown-linux-gnu

- .travis.yml
- docker/i686-linux-android/Dockerfile
After the ndk update used to build libstd https://github.com/rust-lang/rust/pull/45580, i686-linux-android binaries stopped working https://github.com/japaric/cross/issues/143. It's seem that the new toolchain is emitting instructions that the default qemu-i386 cpu does not support. Using -cpu n270 (common in android i686 phones), fix the problem.
Fixes https://github.com/japaric/cross/issues/143.
> Use -cpu n270 to run i686-linux-android binaries

- README.md
- docker/i686-unknown-freebsd/Dockerfile
- docker/sparcv9-sun-solaris/Dockerfile
- docker/x86_64-sun-solaris/Dockerfile
- docker/x86_64-unknown-dragonfly/Dockerfile
- docker/x86_64-unknown-freebsd/Dockerfile
- docker/x86_64-unknown-netbsd/Dockerfile
The g++ is already built, but is not referenced as an environment variable.
Adds the missing environment variables and documents them in README.
> Add C++ support for BSDs and Solaris

- .travis.yml
- Cargo.lock
- Cargo.toml
- README.md
- ci/script.sh
- docker/dragonfly.sh
- docker/freebsd.sh
- docker/i686-pc-windows-gnu/Dockerfile
- docker/mingw.sh
- docker/netbsd.sh
- docker/solaris.sh
- docker/windows-entry.sh
- docker/x86_64-pc-windows-gnu/Dockerfile
- src/errors.rs
- src/main.rs
This fixes almost all current build issues.  Only two issues are left:
- thumb* tests, which requires using https://github.com/japaric/utest instead of https://github.com/japaric/cortest
- netbsd build, which is failing with libc linking issues
> Fix build issues

- docker/aarch64-unknown-linux-gnu/Dockerfile
- docker/arm-unknown-linux-gnueabi/Dockerfile
- docker/armv7-unknown-linux-gnueabihf/Dockerfile
- docker/i586-unknown-linux-gnu/Dockerfile
- docker/i686-unknown-linux-gnu/Dockerfile
- docker/powerpc-unknown-linux-gnu/Dockerfile
- docker/x86_64-unknown-linux-gnu/Dockerfile
I'm currently writing Rust bindings for a C project which only supports CMake >= 3.1. I've choosen 3.5.1 as that is the version which is available on Ubuntu 16.04.
> Upgrade CMake to at least 3.5.1 on all images

- build.rs
- src/docker.rs
- src/main.rs
- src/rustup.rs
In the current form, cross needs to known every target its supports.
This makes things too restrict. For example, its not possible to use a
custom target image for a target that cross does not provides a docker
image (like aarch64-unknown-linux-musl, for example). Cross refuses to
execute saying it does not support the specified target. Besides that,
to add a new docker image the cross code needs to be changed.
This changes simplifies the Target enum to have only two variants:
BuiltIn and Custom. Cross needs to known if a target is a custom target
so it can call xargo, otherwise, all BuitIn targets can be uniformly
handled.
> Simplify Target to use only to cases: BuiltIn and Custom

- .travis.yml
- docker/armv7-unknown-linux-gnueabihf/Dockerfile
- docker/i686-unknown-linux-gnu/Dockerfile
- docker/linux-image.sh
- docker/linux-runner
- docker/mips-unknown-linux-gnu/Dockerfile
- docker/mips64el-unknown-linux-gnuabi64/Dockerfile
- docker/mipsel-unknown-linux-gnu/Dockerfile
- docker/powerpc-unknown-linux-gnu/Dockerfile
- docker/powerpc64-unknown-linux-gnu/Dockerfile
- docker/powerpc64le-unknown-linux-gnu/Dockerfile
- docker/qemu.sh
- docker/s390x-unknown-linux-gnu/Dockerfile
- docker/sparc64-unknown-linux-gnu/Dockerfile
- docker/x86_64-unknown-linux-gnu/Dockerfile
Add qemu-system support for the following targets:
- aarch64-unknown-linux-gnu
- armv7-unknown-linux-gnueabihf
- i686-unknown-linux-gnu
- mips-unknown-linux-gnu
- mipsel-unknown-linux-gnu
- mips64el-unknown-linux-gnuabi64
- powerpc-unknown-linux-gnu
- powerpc64-unknown-linux-gnu
- powerpc64le-unknown-linux-gnu
- s390x-unknown-linux-gnu
- sparc64-unknown-linux-gnu
- x86_64-unknown-linux-gnu
Running `cross test` fails for `s390x-unknown-linux-gnu` and `sparc64-unknown-linux-gnu`, but `cargo run` works. This maybe be a bug in qemu or rustc.
Debian does not have a port for `mips64-unknown-linux-gnuabi64`. Support for arm targets can be add later, but I think a custom kernel will be need.
musl targets can get qemu-system support latter.
> Add  qemu-system support for more targets

- src/docker.rs
This PR add DOCKER_OPTS variable to pass some custom options to `docker run`.
For example, the crate using `ptrace` syscall internally can't be tested by cross, because `ptrace` is not allowed in docker by default.
So I want to specify additional options to allow `ptrace` like below.
```
DOCKER_OPTS="--cap-add=SYS_PTRACE --security-opt=seccomp=unconfined" cross test
```
> Add DOCKER_OPTS variable

- ci/script.sh
- src/cargo.rs
Without this, rustc was being run outside docker and thus not running
with the correct system tools and libraries.
Fixes #239.
> `cargo bench` needs an interpreter like `cargo test`.

- README.md
AFAICT there is in fact not a "default Docker image that ... provides a C environment that tries to cover the most common cross compilation cases". I've never used `cross` but I believe the changes after this PR accurately reflect what the codein this repository does.
> Clarify use of docker images in README.md

- build-docker-image.sh
- docker/linux-image.sh
- src/cargo.rs
- src/docker.rs
- src/main.rs
- src/rustc.rs
- src/rustup.rs
This automatically installs the Linux toolchain on macOS, so it can be used by the Docker images, and then installs the targets for the Linux toolchain instead of the default one.
> Fix toolchain path on macOS.

- docker/dragonfly.sh
- docker/linux-image.sh
- src/cargo.rs
- src/main.rs
- src/rustup.rs
Automatically install `clippy` for the appropriate toolchain. Also fixes `rust-src` not being installed for the appropriate toolchain on macOS.
>  Add support for clippy.

- .travis.yml
- README.md
- docker/arm-unknown-linux-gnueabihf/Dockerfile
I took the suggestion from https://github.com/rust-embedded/cross/pull/158#issuecomment-360763050 and used a pre-compiled toolchain.
There are two commits here, the first one uses https://github.com/raspberrypi/tools, in the second one I switched to https://toolchains.bootlin.com/releases_armv6-eabihf.html.
I am not sure however if the `sysroot` is set correctly, since everything except `qemu` also works without `LD_LIBRARY_PATH=/usr/arm-linux-gnueabihf/lib:/usr/arm-linux-gnueabihf/arm-buildroot-linux-gnueabihf/lib`.
> Add `arm-linux-gnueabihf`.

- src/docker.rs
On macOS, running `cross clippy --target=...` will fail with a cryptic error message
```
/cargo/bin/cargo-clippy: 12: /cargo/bin/cargo-clippy: Syntax error: "(" unexpected (expecting ")")
```
because it tries running the Darwin `cargo-clippy` binary in `$CARGO_HOME/bin` instead of the one inside the specific toolchain.
> Don't mount cargo `bin` in Docker container.

- docker/armv7-unknown-linux-musleabihf/Dockerfile
Fixes #252.
Signed-off-by: Brian Smith <brian@briansmith.org>
> Stop hard-coding NEON support for armv7-unknown-linux-musleabihf.

- src/docker.rs
This should allow `cross` to work on both non-SELinux enabled systems
and SELinux ones.
I've tested on Fedora 29 for SELinux system.
Fixes #112 that was originally reported from Fedora as well I believe.
> Support mounting on SELinux

- README.md
* Fix a typo in "QEMU bug sand"
* Add a link for QEMU
* Clarify and simplify various other things about the wording
The diff looks worse than the changes are. I tried to keep to the 80-column width since it looked like the rest of the text was that way. GitHub's “rich diff” seems to help here.
> Minor improvements to wording

- .travis.yml
Docker Hub images should always be pushed, also without a tag.
> Fix Travis deployment.

- .travis.yml
- build-docker-image.sh
- src/docker.rs
Pulling an image from Docker Hub is approximately twice as fast as extracting it from the Travis cache.
>  Improve caching.

- README.md
- src/main.rs
Closes https://github.com/rust-embedded/cross/issues/148.
> Automatically download `-apple-ios` components on macOS.

- docker/linux-runner
Fixes `powerpc64le` using `qemu-ppc64` (which doesn't exist) instead of `qemu-ppc64le`.
> Fix default runner.

- docker/qemu.sh
Use qemu-3.0.1 for all powerpc architectures, and 4.1.0 for everything else.
Note: @reitermarkus, this requires bash for the scripting language, not shell, which the Dockerfiles currently use. I'm not sure if this is a deal-breaker.
Closes https://github.com/rust-embedded/cross/issues/313.
> Patch for breaking 32-bit float conversions on ppc (#313).

- src/docker.rs
When stdin is not a TTY, cross fails because it still passes `-i` to `docker run`, which makes Docker fail like so:
```
the input device is not a TTY
```
Apparently GitHub Actions doesn't have a TTY as stdin, so this is the fix to make cross work with GitHub Actions.
> Fix cross when stdin is not a TTY

- azure-pipelines.yml
- docker/linux-runner
Closes https://github.com/rust-embedded/cross/issues/314.
> Default to `native` runner.

- docker/Dockerfile.x86_64-linux-android
- docker/linux-image.sh
The Rust Android target uses CPU features such as +popcnt and +sse4.2 which
are not available on Penryn. List the used CPU exactly the same way as
it is listed in the Rust target [here](https://github.com/rust-lang/rust/blob/master/src/librustc_target/spec/x86_64_linux_android.rs#L7).
Please publish an updated docker image sooner rather than later.
> Fix Android’s CPU features

- Cargo.lock
- Cargo.toml
- README.md
- src/docker.rs
- src/errors.rs
- src/main.rs
- Via the new container_engine parameter in Cross.toml, the user can now
specify whether they want to use Podman or Docker.
- Several changes to src/docker.rs to pass in different options based on whether
docker or podman is being used. This also mandates the use of `--userns host`
which does require bumping the minimum Docker version.
- Updates to the code base based on rustfmt and clippy recommendations.
> Adding support for Podman

- README.md
- src/docker.rs
The project directory was previously deliberately mounted as read-only since “well behaved crates should only ever write to `$OUT_DIR` and never modify `$CARGO_MANIFEST_DIR`”.  That however, breaks the `--locked` flag and is not worth the additional complexity.
Fixes https://github.com/rust-embedded/cross/issues/346.
> Allow writing `Cargo.toml` in project directory.

- docker/Dockerfile.aarch64-unknown-linux-gnu
- docker/Dockerfile.arm-unknown-linux-gnueabi
- docker/Dockerfile.arm-unknown-linux-gnueabihf
- docker/Dockerfile.armv7-unknown-linux-gnueabihf
- docker/Dockerfile.i686-unknown-linux-gnu
- docker/Dockerfile.x86_64-unknown-linux-gnu
Images started failing to build with Ubuntu 14.04.
This is a breaking change, but the next version will be 0.2.0 in any case.
This brings up the question whether we should just bump all images to use 18.04 so we can have a common base image for all of them. To keep supporting the oldest version is clearly not feasible in the long run since images will keep breaking.
> Bump Ubuntu 14.04 to 16.04.

- Cargo.lock
- Cargo.toml
- src/docker.rs
- src/extensions.rs
> Use a "SafeCommand" type which `Debug`s as a shell-escaped String when running build commands inside Docker.

- src/cli.rs
- src/docker.rs
- src/main.rs
Closes https://github.com/rust-embedded/cross/pull/340.
> Support `--target-dir`.

- azure-pipelines.yml
- build-docker-image.sh
- ci/azure-install-rust.yml
- ci/test.sh
- docker/common.sh
- docker/linux-image.sh
Also, increase timeout for the build step.
> Build docker images in separate step.

- CHANGELOG.md
The Unreleased and v0.2.0 links in the Changelog were not pointing to what you intended them to point to.
> docs(CHANGELOG): fix version links

- src/docker.rs
The PKG_CONFIG_ALLOW_CROSS env variable is required to cross compile
various crates such as openssl.
Fix #383
> docker: define PKG_CONFIG_ALLOW_CROSS

- build-docker-image.sh
This avoids overwriting the local image when making changes to images locally.
> Avoid pulling if image already exists locally.

- Cargo.lock
- Cargo.toml
- README.md
- azure-pipelines.yml
- src/cli.rs
- src/docker.rs
- src/main.rs
When using docker-in-docker, for example in dev or CI containers, one
normally gives access to the host docker environment to the parent container.
If the container spins up another child container, and wishes
to share a directory, one needs to compute the correct paths from
view of the host system.
If the environment variable `CROSS_DOCKER_IN_DOCKER=true`, we call 
`docker inspect $HOSTNAME`, to learn about details of the current container.
The `Mounts` field contains information about all mounts from the host
into the current container. The `GraphDriver` field gives us information
about the storage driver and the location of the contains root directory on the host system. Based on these information we compute
a table of all container mounts (`source->destination`).
When starting a child …
> Docker in docker

- README.md
- azure-pipelines.yml
- docker/Dockerfile.riscv64gc-unknown-linux-gnu
- docker/linux-image.sh
rust support for riscv64gc-unknown-linux-gnu [is not yet advertised](https://forge.rust-lang.org/release/platform-support.html), but [is merged](https://github.com/rust-lang/rust/pull/66661).
There are [issues](https://github.com/rust-lang/rust/issues/62117) with riscv64gc-unknown-linux-gnu but it works well enough to build many crates (including rustc).
> Add riscv64gc-unknown-linux-gnu support

- src/docker.rs
As discussed here: https://github.com/rust-embedded/cross/pull/387#discussion_r408257447
The check is not needed to allow to mount paths that are mounted in the first docker with the same path.
> Allow to mount host path in docker-in-docker mode

- docker/linux-image.sh
It's needed when generating an image based on Ubuntu 18.04 or Debian
Buster. Adding it makes it easier for users to create such image as they
can just re-use the existing script without having to modify it.
It doesn't matter when building with Ubuntu 16.04 as the package is
already present in the base image so it's just skipped.
> docker: linux-image: add gnupg to local deps

- docker/Dockerfile.arm-unknown-linux-gnueabihf
Currently, installing the toolchain for `arm-unknown-linux-gnueabihf`
uses `xz-utils` which gets pruned. This also removes `pkg-config`, so
remove the prune altogether to keep both packages. `curl` is also kept
as that was originally installed in `common.sh` as well.
Fixes #422
> Prevent pkg-config from being removed in image

- README.md
- src/main.rs
This is an attempt to fix https://github.com/rust-embedded/cross/issues/325.
We want to use the target `x86_64-alpine-linux-musl` (available from alpine's rustc) to build musl-based binaries and when using cross with something not in the standard rustc/rustup targets, cross errors out as detailed in the issue above. 
For a non-standard target, cross defaults to using `xargo` right now (behavior introduced in https://github.com/rust-embedded/cross/pull/217), but in our case, since we want `cargo` to run ultimately, I had to also ensure that setting `xargo = false` actually works from the cross config file. If there's a better way of handling this without breaking the current default behavior, please let me know.
Also updated the docs on xargo usage accordingly (including the parts that …
> Allow users to pick cargo for custom target builds

- README.md
- azure-pipelines.yml
This PR adds a documented MSRV, per https://github.com/rust-embedded/wg/issues/445
As far as I can tell none of the Azure pipelines use Xargo or nightly Rust, so I think this small change should be sufficient, but we'll see what CI makes of it.
> Change CI to build with Rust 1.32 and document that as MSRV

- docker/Dockerfile.armv7-unknown-linux-musleabihf
- docker/Dockerfile.x86_64-unknown-linux-gnu
- docker/Dockerfile.x86_64-unknown-linux-musl
- docker/linux-image.sh
- docker/musl.sh
Several reasons, including but not limited to:
1) MUSL-compiled OpenSSL benefits from MUSL versions 1.2.0 and up, otherwise it needs to be badly patched, see https://github.com/fornwall/rust-static-builder/issues/3#issuecomment-638085541.
2) DWARFv2 compressed debugging symbols mess up with old toolchains and linkers, see https://github.com/rust-bio/rust-htslib/pull/231.
> Bump Ubuntu container version and MUSL-related libs

- README.md
The custom dockerfile example in the README targets cross version 0.1.16, [and is known to not actually work as-is](https://github.com/rust-embedded/cross/commit/3b07a08aa8739a9f22450ceecc56531d108661d5).
The fix for this particular issue was released with cross 0.2, thus this PR bumps the cross version.
This became an issue in my use case as I wanted to cross-compile to a raspberry Pi, and needed to install some external libraries not included in the base images, and ran into issues such as #149 and #35 while attempting to follow the recommendation in the readme.
Bumping the cross version to 0.2.x resolved the above issues for me, and this PR is to help other users that may find themselves running into the same issues when following the readme closely.
> Bump README custom-container cross version to incorporate fixes

- docker/solaris.sh
The libc-dev and librt-dev packages have been replaced by libc and librt.
> Fix solaris build

- src/cargo.rs
- src/main.rs
this will enable running `cargo metadata` in the container instead of on the host.
> add cross metadata

- src/rustup.rs
The issue is that `cross` is trying to call `rustup toolchain add XX` on every run when toolchain overrides are in use.
Replication & more detail on the issue is given in this repo: https://github.com/kay/cross-toolchain-override-bug
This uses a `rust-toolchain` file to override you can also replicate using `rustup override set 1.45.1` as described [here](https://doc.rust-lang.org/edition-guide/rust-2018/rustup-for-managing-rust-versions.html#managing-versions)
Going by the latest rustup source, [this is the relevant code](https://github.com/rust-lang/rustup/blob/90bd7351693965af52cee7f7ab84a8bbb65706c7/src/cli/common.rs#L488) that enumerates the various annotations outputted for toolchains:  and it looks like `(default)` and `(override)` are the only ones that may be output for running …
> Fix bug with rustup toolchain overrides causing redundant channel update syncing

- README.md
- src/docker.rs
By default, `cross` tries to use Docker or Podman, with the former to have priority. In you want to use other container engine or explicitly choose one you can set the name of binary (or the path) in `CROSS_CONTAINER_ENGINE` environment variable.
For example in case you want use Podman, you can set `CROSS_CONTAINER_ENGINE=podman`.
> Add a way to choose Podman instead of Docker

- README.md
- azure-pipelines.yml
- docker/Dockerfile.i686-pc-windows-gnu
- docker/mingw.sh
The build command in mingw.sh script was failing but the script continued to run and returned 0. The result was that the mingw toolchain with sjlj was being used in the image, not the one with dwarf expectation we are trying to build!
I set the option -e and fixed the script.
> Fix i686-pc-windows-gnu

- docker/musl.sh
cc @reitermarkus, this is what caused the MUSL CI failure in https://github.com/rust-embedded/cross/pull/475
Upstream Rust has also been hitting this and has created this mirror.
> Fix MUSL CI

- README.md
On #472 PR I used `[Docker]` and `[Podman]` however I didn't notice that they were not defined.
> Fix link text in README.md

- docker/Dockerfile.aarch64-linux-android
- docker/Dockerfile.arm-linux-androideabi
- docker/Dockerfile.armv7-linux-androideabi
- docker/Dockerfile.i686-linux-android
- docker/Dockerfile.x86_64-linux-android
- docker/android-ndk.sh
- docker/android-system.sh
- docker/linux-image.sh
the Dockerfiles try to use linux-image-4.19.0-10 which no longer exists in the debian package repository; this is making CI fail: https://dev.azure.com/rust-embedded/cross/_build/results?buildId=772&view=logs&j=e6deedce-f53c-5dcc-524e-14349f140ffd&t=9e60ab89-47e0-5dc9-e657-a2fbb695cbf9&l=6521
this PR updates the package version (revision?) to linux-image-4.19.0-**11**
> bump linux-image version to fix CI

- docker/Dockerfile.aarch64-unknown-linux-musl
- docker/aarch64-linux-musl-gcc.sh
instead use a linker wrapper to work around issue rust-lang/rust#46651
not setting RUSTFLAGS inside the container lets end users pass rustc flags via `.cargo/config`
this is an alternative to #464 that doesn't require bumping the MSRV of the `aarch64-unknown-linux-musl` target (that is the aarch64-musl image will continue to work with Rust 1.42 where bug rust-lang/rust#46651 is still presen )
> don't set RUSTFLAGS in aarch64-musl image

- docker/linux-image.sh
- src/docker.rs
> use runner setting specified in Cross.toml

- docker/freebsd-extras.sh
https://pkg.freebsd.org/FreeBSD:12:i386/quarterly/All/openssl-1.1.1h,1.txz returns 404 and it's making the freebsd build job fail in CI
OpenSSL 1.1.1i was released ~8 days ago and that URL seems to work so this PR bumps the openssl version
> fix ci: bump openssl version in freebsd

- azure-pipelines.yml
- docker/freebsd-extras.sh
- docker/linux-image.sh
Docker images fail to build in pipeline because linux image packages was updated in debian repo.
I updated to 4.19.0-14
> fix image builds with update of dependencies

- src/docker.rs
`CROSS_CONTAINER_UID` and `CROSS_CONTAINER_GID` can now be used to control the user and group ID's passed to Docker.
I ran into this when trying to setup a Github-Action that runs on MacOS and uses docker-machine which wasn't working. I then found https://github.com/rust-embedded/cross/issues/389 which described the solution of updating the UID and GID which I've confirmed works. This change should make it easier for users to solve for the same issue without making a fork.
> Added environment variables to control the UID and GID in the container

- docker/freebsd-extras.sh
- src/main.rs
This PR enables more freedom when choosing custom host/target combinations and simplifies (unifies) logic and behavior regarding when to build natively (using local toolchain) and when to use docker image based toolchain. If users explicitly passes `--target ...` option to `cross` it will always use docker image based toolchain (unless a target explicitly opts-out) and only use the local toolchain if `--target` option is not present.
Furthermore, no longer make any assumptions about the host, and let users use any host. It is the user's choice and responsibility to choose a working host platform and `cross` should not artificially limit use cases.
This PR also addresses:
- [436](https://github.com/rust-embedded/cross/issues/436)
> Add support for more hosts and simplify/unify host support checks

- .github/workflows/changelog.yml
Adds a GHA check to ensure every PR is accompanied by a edit of CHANGELOG.md to list the changes so we don't run into the usual issue of having to come up with all entries when someone requests a release.
> Add changelog.yml GHA workflow

- build.rs
One of the Arch Linux rebuilders has trouble reproducing the [cross binary](https://wolfpit.net/rebuild/api/v0/builds/24560/diffoscope) we distribute in Arch Linux. We assume this is because it runs a different filesystem than the official build server, causing `fs::read_dir` to yield the directory content in a different order.
This patch explicitly sorts the directory content of docker/ in build.rs before constructing a list that gets embedded in the binary.
Full writeup can be found over here: https://twitter.com/sn0int/status/1418254640324521997
> Repro builds: Deterministically iterate through docker/ folder

- src/cli.rs
When parsing argument `parse()` function in `src/cli.rs`  splits the argument string without checking length which results in panic when splitting empty string.
This PR pix that issue by introducing `continue` on empty string.
> Do no panic when passed empty string as argument. closes #466

- CHANGELOG.md
> fix: update changelog for pending release

- Cargo.lock
- Cargo.toml
This crate only uses semver transitively through the rustc_version crate. It does not need to directly depend on semver.
> Remove explicit semver dependency

- src/docker.rs
Populating this variable fails under Linux if the local user doesn't have a username. This may happen when using Docker and mapping a user ID from the host into a container, such as when using `--user=$(id -u):$(id -g)`. I suggest making the `USER` environment variable passed to `docker` optional, which allows `cross` to work in the given scenario.
> Make the `USER` variable to `docker` optional

- docker/freebsd-extras.sh
- docker/freebsd.sh
This is required to build some native projects
which is build with -fstack-protector when linked.
Also update sqlite3 version (quarterly is updated)
> FreeBSD: add libssp

- src/rustup.rs
this is needed bc of some bug(?) in rustup not being able to install the necessary toolchain without error using the `default` profile, so the `minimal` profile is needed.
see my comment in the rustup project regarding this issue: https://github.com/rust-lang/rustup/issues/2661#issuecomment-783717159
this is the error I get when running cross
```
$ rm -rf ~/.rustup                                       
$ cross build --target aarch64-unknown-linux-gnu
warning: toolchain 'nightly-x86_64-unknown-linux-gnu' may not be able to run on this system.
warning: If you meant to build software to target that platform, perhaps try `rustup target add x86_64-unknown-linux-gnu` instead?
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2021-02-22, rust version …
```
> specify the `minimal` profile when installing rust toolchain (due to bug in rustup?)

- README.md
- src/main.rs
This allows for the use of a `CROSS_CONFIG` environment variable to explicitly set the path to a `Cross.toml` file to use for builds.
> Add support for `CROSS_CONFIG` environment var

- .github/workflows/changelog.yml
- build-docker-image.sh
https://github.com/cross-rs/cross/actions/runs/1978039245 merge of #609 failed, this should fix that
> don't push and load at the same time

- docker/common.sh
Closes #174
This PR adds clang as a common build tool.
The libclang will be used by bindgen so It's better to have clang on all platforms so I add to common.sh
This works for bindgen for the following targets with `ffmpeg-next` of `libavformat`, `libavcodec`, and `libavutil`  with my built ffmpeg binaries:
- `x86_64-pc-windows-gnu`
- `x86_64-unknown-linux-musl`
I couldn't test `x86_64-unknown-linux-gnu` because of #455
<details>
<summary>#455 error message. This will be happened without this PR (with the image from DockerHub)</summary>
```
Compiling libc v0.2.107
Compiling ffmpeg-sys-next v4.4.0
error: failed to run custom build command for `libc v0.2.107`
Caused by:
process didn't exit successfully: `/target/release/build/libc-e4387d0c49bcd20f/build-script-build` (exit status: 1)
--- …
```
> add clang as a common build tool

- src/cargo.rs
Hi, this pr adds sub-commands shortcuts `['b','c','r', 't']` to the cli.
The main reason is currently the error when using them is misleading.
Example:
this command:
`cross b --target arm-linux-androideabi`
outputs this error: 
`error: linking with `cc` failed: exit code: 1` 
which took me a while to figure out that cross is not recognizing the sub-command and is falling-back to cargo.
Also they are useful to have.
> Add cross subcommands shortcuts

- docker/Dockerfile.i686-unknown-freebsd
- docker/Dockerfile.x86_64-unknown-freebsd
The environment variable has broken procedural macro crates which depend on `libsqlite3-sys`, such as `migrations_macros`.
Even without the variable, `libsqlite3-sys` finds the correct path anyway.
This fixes #520, as shown in the CI at [tesaguri/cross-freebsd-diesel_migrations-test] repository.
~Additionally, this PR updates `freebsd{,-extras}.sh` to use OpenSSL from the base system, because the URLs `https://pkg.freebsd.org/FreeBSD:12:{amd64,i686}/quarterly/All/openssl-1.1.1j,1.txz` returns `404` now.~
[tesaguri/cross-freebsd-diesel_migrations-test]: https://github.com/tesaguri/cross-freebsd-diesel_migrations-test
> don't set `SQLITE3_LIB_DIR` in FreeBSD images

- CHANGELOG.md
- build-docker-image.sh
- docker/linux-image.sh
Also use pushed images as cache.
> Improve Docker caching.

- .github/workflows/ci.yml
- CHANGELOG.md
- build-docker-image.sh
- build.rs
- src/cargo.rs
- src/cli.rs
- src/config.rs
- src/docker.rs
- src/extensions.rs
- src/id.rs
- src/main.rs
Allow trying individual targets.
Closes https://github.com/cross-rs/cross/issues/651.
> Support bors try arguments.

- src/config.rs
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
> Fix 'clippy' warnings

- src/main.rs
I've lost some good days struggling with errors because I've created a file named cross.toml and it wouldn't affect the build, because the name was not capitalized correctly. So, I think it should be cool if cross could warn the user if there's a file with a capitalization problem present on the project root.
> Warn user if there's a file cross.toml with wrong capitalization

- .github/workflows/ci.yml
- CHANGELOG.md
- docker/Dockerfile.mips64-unknown-linux-muslabi64
- docker/Dockerfile.mips64el-unknown-linux-muslabi64
> Add mips64-unknown-linux-muslabi64 and mips64el-unknown-linux-muslabi64 support

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/rustc.rs
- cargo: Update all minor dependencies
- cargo: Upgrade nix to 0.23.1
- cargo: Upgrade which to 4.2.4
- cargo: Upgrade rustc_version to 0.4.0
> Upgrade all dependencies to latest releases

- docker/Dockerfile.aarch64-unknown-linux-gnu
- docker/Dockerfile.arm-unknown-linux-gnueabi
- docker/Dockerfile.armv5te-unknown-linux-gnueabi
- docker/Dockerfile.armv7-unknown-linux-gnueabihf
- docker/Dockerfile.asmjs-unknown-emscripten
- docker/Dockerfile.i586-unknown-linux-gnu
- docker/Dockerfile.i686-unknown-linux-gnu
- docker/Dockerfile.mips64-unknown-linux-gnuabi64
- docker/Dockerfile.mips64el-unknown-linux-gnuabi64
- docker/Dockerfile.mipsel-unknown-linux-gnu
- docker/Dockerfile.powerpc-unknown-linux-gnu
- docker/Dockerfile.powerpc64-unknown-linux-gnu
- docker/Dockerfile.powerpc64le-unknown-linux-gnu
- docker/Dockerfile.riscv64gc-unknown-linux-gnu
- docker/Dockerfile.s390x-unknown-linux-gnu
- docker/Dockerfile.sparc64-unknown-linux-gnu
- docker/Dockerfile.thumbv6m-none-eabi
- docker/Dockerfile.thumbv7em-none-eabi
- docker/Dockerfile.thumbv7em-none-eabihf
- docker/Dockerfile.thumbv7m-none-eabi
- docker/Dockerfile.x86_64-pc-windows-gnu
Fixed #590, by preventing caching of layers which can prevent builds
from completing when a step fails, causing the package repository to
become out-of-date and the install step to fail.
> Ensure apt-get update is run during Docker builds.

- CHANGELOG.md
- src/docker.rs
When running inside NixOS or using Nix packaging we need to add the Nix
Store to the running container so it can load the needed binaries.
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
> docker: Add Nix Store volume support

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- docs/cross_toml.md
- src/config.rs
- src/cross_toml.rs
- src/main.rs
This PR implements the deserialization of the `Cross.toml` config using `serde`. It can therefore be seen as some preliminary work on the issues #657, #664, and is related to #532 on #624.
I added some basic documentation as module-level documentation, although I'm not sure whether this is the best place for that. Ideally it should be documentated in the `README.md` at some point. Furthermore, `CrossToml` lives in its own module, but a more suitable place might be the `config` module.
> Implement `Cross.toml` deserialization using `serde`

- CHANGELOG.md
- docs/cross_toml.md
- src/config.rs
- src/cross_toml.rs
- src/main.rs
- src/rustc.rs
This implements #368 
This feature allows to specify the default target to build either in `Cross.toml`
```toml
[build]
target = "aarch64-unknown-linux-gnu"
```
or by setting `CROSS_BUILD_TARGET` to avoid the need to always specify `--target`.
I've opted for `build.target` as this resembles the configuration of [cargo](https://doc.rust-lang.org/cargo/reference/config.html#buildtarget).
> Allow setting default build target

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/docker.rs
This fixes windows usage.
It also tries to fix windows builds when using `env.volumes` by making windows compatible
paths for `env.volumes`
not using env.volumes will now also mount the project in `/project` again
> make env.volumes only change package path when used

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/config.rs
- src/cross_toml.rs
- src/main.rs
> warn on unknown fields and confusable targets

- CHANGELOG.md
- ci/test.sh
- docker/Dockerfile.aarch64-linux-android
- docker/Dockerfile.arm-linux-androideabi
- docker/Dockerfile.armv7-linux-androideabi
- docker/Dockerfile.i686-linux-android
- docker/Dockerfile.x86_64-linux-android
- docker/android-ndk.sh
- docker/android-system.sh
- src/docker.rs
- src/main.rs
This PR updates Android NDK version and API version as the same as libc crate.
https://github.com/rust-lang/libc/blob/master/ci/android-install-ndk.sh
Fix https://github.com/rust-embedded/cross/issues/195
> Update Android NDK version and API version

- README.md
This PR adds libc version of android because bionic is provided as libc on android.
QEMU version is added too.
> Add android libc version

- docker/dropbear.sh
- docker/linux-image.sh
The broken link prevented Docker images from building.
> Fix broken link in `dropbear.sh`

- Cargo.lock
- Cargo.toml
This reduces cross's compile time slightly, and removes memoffset as an indirect dependency.
> Upgrade nix to 0.24, limit features

- .github/bors.toml
This change removes the required approvals condition that was required by convention before we switched to our own organization.
With this change, more care has to be taken into account from maintainers (who have `bors r+` privileges) when merging their own PRs, but this also allows quicker development when members are not available to review prs and sufficient thought has been taken into account. Ideally, "bad" changes would be caught by CI.
For the above reason, before merging this I think it'd be good if current @cross-rs/maintainers could sign off and approve the PR (leave a tick next to your name and possibly approve via review) before it's ultimately merged (we do not currently have a policy on how breaking changes or expectations are managed, so this is kinda arbitrary but takes …
> don't require other approval for bors

- src/main.rs
- src/rustc.rs
- src/rustup.rs
- src/tests.rs
on non-linux hosts, warn when toolchain is out of date.
```
$ cross build
Warning: using older rustc `1.61.0-nightly (9f4dc0b4d 2022-03-23)` for the target. Current active rustc on the host is `rustc 1.62.0-nightly (879aff385 2022-04-20)`.
> Update with `rustup update --force-non-host nightly-x86_64-unknown-linux-gnu`
```
> warn when used toolchain is out-of-date

- CHANGELOG.md
- src/cli.rs
- src/main.rs
Converts relative target directories to absolute paths, to avoid creating the target directory in the sysroot. This keeps the prior behavior if the provided target directory is an absolute path.
Fixes #581.
> Convert --target-dir to use absolute paths.

- CHANGELOG.md
- src/main.rs
When using docker, the target directory is mounted at `/target`. However, when falling back to the host cargo, if we provide a custom target directory, we incorrectly pass it as `--target-dir /target`. To rectify this, this PR passes the original command-line arguments to cargo.
Fixes #619.
> Use host target directory when calling host cargo.

- CHANGELOG.md
- src/cargo.rs
cargo-deb is not installed in the pre-built images, but `cross deb` runs in docker rather than falling back to the host.
Closes #717.
> Remove deb subcommand.

- CHANGELOG.md
- src/cli.rs
Allow values of 0, 1, so values other than `true` or `false` can be provided. `VAR=0`, `VAR=`, `VAR=-0`, or `VAR=false` will evaluate to false, while the rest will evaluate to true.
Affects #661 and #721.
> Evaluate boolean environment variables as truthy or falsey.

- CHANGELOG.md
- README.md
- src/cli.rs
- src/main.rs
- src/rustup.rs
This partially addresses #225.
This only works on nightly, due to the use of the unstable feature [doctest-xcompile](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#doctest-xcompile)
The relevant tracking issues are:
- https://github.com/rust-lang/cargo/issues/7040
- https://github.com/rust-lang/rust/issues/64245
If the subcommand is `test` and the compiler is nightly, we provide the `-Zdoctest-xcompile` flag if `CROSS_UNSTABLE_ENABLE_DOCTESTS=true`.
> Add preliminary support for running doctests.

- .github/workflows/ci.yml
- CHANGELOG.md
- docker/Dockerfile.aarch64-linux-android
- docker/Dockerfile.arm-linux-androideabi
- docker/Dockerfile.i686-linux-android
- docker/Dockerfile.x86_64-linux-android
- docker/android-runner
Android binaries currently fail to run linking against certain dependencies, because `libc++_shared.so` is not found, so ensure the library is preloaded via `LD_PRELOAD`. This creates a simple `android-runner` file, so any additional changes can be added there.
This merely links to the proper `libc++_shared.so`, so it doesn't fix other issues. The [hello world project](https://github.com/cross-rs/rust-cpp-hello-word) now compiles and runs on `aarch64-linux-android`, but not `i686-linux-android`, which seems to be entirely unrelated (likely a permission error on the cloud Fedora server I'm running).
```text
error getting old personality value: Operation not permitted
libc: error getting old personality value: Operation not permitted
Aborted (core dumped)
```
Linked Issues: #82
> Add android runner to run android binaries.

- CHANGELOG.md
- src/cargo.rs
- src/cli.rs
- src/extensions.rs
- src/main.rs
`cross --list` should list the subcommands present for cargo in the image, rather on the host. This works because any option provided before a subcommand has priority over the subcommand. For example, `cargo build --help` prints the help menu for `cargo build`, but `cargo --help build` ignores `build` and prints the help for `cargo`. Therefore, the options `--help`, `--version`, and `--list` can be treated as pseudo-subcommands.
Fixes #715.
> Add --list to known subcommands.

- CHANGELOG.md
- docker/Dockerfile.armv7-linux-androideabi
- docker/Dockerfile.i686-linux-android
- docker/Dockerfile.x86_64-linux-android
- docker/android-runner
Support the `CROSS_DEBUG` and `CROSS_RUNNER` environment variables for android runners.
This allows us to both get debugging information for the Android runner (similar to the Linux runner) and also use a native runner for Android (defaults to Qemu). It also fixes a minor bug where the Android runner was not used on `armv7-linux-androideabi`.
> Support cross debugging and runners on Android.

- CHANGELOG.md
- docker/Dockerfile.aarch64-unknown-linux-gnu
- docker/Dockerfile.arm-unknown-linux-gnueabi
- docker/Dockerfile.arm-unknown-linux-gnueabihf
- docker/Dockerfile.armv5te-unknown-linux-gnueabi
- docker/Dockerfile.armv7-unknown-linux-gnueabihf
- docker/Dockerfile.i586-unknown-linux-gnu
- docker/Dockerfile.i686-unknown-linux-gnu
- docker/Dockerfile.mips-unknown-linux-gnu
- docker/Dockerfile.mips64-unknown-linux-gnuabi64
- docker/Dockerfile.mips64el-unknown-linux-gnuabi64
- docker/Dockerfile.mipsel-unknown-linux-gnu
- docker/Dockerfile.powerpc-unknown-linux-gnu
- docker/Dockerfile.powerpc64-unknown-linux-gnu
- docker/Dockerfile.powerpc64le-unknown-linux-gnu
- docker/Dockerfile.riscv64gc-unknown-linux-gnu
- docker/Dockerfile.s390x-unknown-linux-gnu
- docker/Dockerfile.sparc64-unknown-linux-gnu
This adds support for pkg-config to all `*-linux-gnu` images, since `pkg-config` is already installed on these images. We export `PKG_CONFIG_PATH` which allows packages installed from `apt` to be automatically added to the search path when linking.
See [cross_dbus_pkgconfig](https://github.com/Alexhuszagh/cross_dbus_pkgconfig) for examples building and linking against a library with a D-BUS dependency.
Closes #404.
> Add `PKG_CONFIG_PATH` to all `*-linux-gnu` images.

- CHANGELOG.md
- docker/Dockerfile.i686-unknown-freebsd
- docker/Dockerfile.x86_64-unknown-freebsd
- docker/freebsd-common.sh
- docker/freebsd-extras.sh
- docker/freebsd.sh
Do not hardcode exact versions of the FreeBSD release, `openssl`, or `sqlite3` versions. Rather, use the FreeBSD ftp server to determine the latest `12.X` release, and use the package list downloaded to determine the latest `openssl` and `sqlite3` versions.
Since we use a dynamic version of FreeBSD, and have no good way of detecting this later, we write the version and revision to `/opt/freebsd-version`.
Fixes #695.
> Make FreeBSD builds more resilient.

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- docker/Dockerfile.armv7-unknown-linux-gnueabi
- docker/Dockerfile.armv7-unknown-linux-musleabi
- docker/crosstool-config/arm-unknown-linux-gnueabihf.config
Added `armv7-unknown-linux-gnueabi` and `armv7-unknown-linux-musleabi` targets, which target soft-float ARMv7-a processors.
Closes #354.
> Add soft-float ARMv7 targets.

- docker/Dockerfile.x86_64-unknown-linux-gnu
- docker/android-ndk.sh
- docker/android-system.sh
- docker/disabled/dragonfly.sh
- docker/emscripten.sh
- docker/freebsd.sh
- docker/linux-image.sh
- docker/mingw.sh
- docker/musl.sh
- docker/netbsd.sh
- docker/solaris.sh
Remove all local use of installing manually via the package manager, using `install_packages` and `purge_packages` rather than use redundant code. Simplifies our shell scripts to build docker images.
Still a draft because I'm currently testing it on all images.
> Refactor code to use install_packages and purge_packages.

- .github/workflows/ci.yml
Allow using `bors try --target ... --target ...`, allowing multiple arguments rather than just a single one.
> Add support for multiple bors targets.

- CHANGELOG.md
- src/docker.rs
Allow the following syntax:
```toml
[build.env]
passthrough = ["VAR=VALUE"]
```
Closes #743.
> Allow variable definitions in env.pasthrough.

- CHANGELOG.md
- docker/android-ndk.sh
Delete unused toolchains to save ~600MB in our total image sizes. This is done by removing the toolchains for other targets in `/android-ndk/sysroot/usr/lib/`.
Closes #739.
> Reduce Android image sizes.

- src/docker.rs
Currently, docker detection fails under a few cases:
1. If `podman_docker` is installed, so the filename is docker but the actual executable is podman.
2. If the executable has a suffix, such as `.exe` on Windows, because we check if the executable `ends_with(DOCKER)`.
The only reliable way to fix both these issues, IE, if the actual engine is docker and not an alias, and if the executable does not contain a suffix, is to query the container engine. This might not be ideal for performance reasons, but is the only reliable way to fix these issues.
Closes #530.
Closes #538.
> Fix docker detection.

- README.md
part of https://github.com/cross-rs/cross/issues/758?
> update readme to mention install from git due to outdated crates version

- ci/extract_image_info.sh
- ci/extract_target_info.sh
Attempts to recreate the table present in README.md, which
can extract the target information for a single target
or for all targets.
Should currently support the following targets:
- Android
- glibc
- musl
- MinGW
- FreeBSD
- NetBSD
- newlib
Closes #686.
This produces the following table:
| Target                               |  libc  |   GCC   | C++ | QEMU  |
|:-:|:-:|:-:|:-:|:-:|
| `aarch64-linux-android`              | 9.0.8  | 9.0.8   | ✓   | 5.1.0 |                                                                                                                           
| `aarch64-unknown-linux-gnu`          | 2.23   | 5.4.0   | ✓   | 5.1.0 |
| `aarch64-unknown-linux-musl`         | 1.2.0  | 9.2.0   | ✓   | 5.1.0 |
| `arm-linux-androideabi`              | 9.0.8  | 9.0.8   | ✓   | …
> Add scripts to validate target info.

- CHANGELOG.md
- README.md
- ci/test.sh
- src/cargo.rs
- src/cli.rs
- src/docker.rs
- src/file.rs
- src/main.rs
- src/tests.rs
This will allow cargo workspaces to work seamlessly with cross, assuming they don't reference anything outside the current workspace root. This change also automatically mounts (if needed) path dependencies.
If they do reference things outside the workspace root, and that fact is not know to `cargo metadata` (e.g, it's not a workspace member or a path dependency), you'll have to mount it with
```toml
[build.env]
volumes = ["THING"]
```
and set `$THING="/path/to/thing"` (we need to work on accessibility for this feature too, a lot of reported issues are solved by it)
I'm sure there is an issue directly related to workspaces, but I can't find any.
fixes #388
> enable cargo workspace and path dependencies to work seamlessly

- .github/workflows/ci.yml
- CHANGELOG.md
- docker/Dockerfile.x86_64-unknown-dragonfly
- docker/dragonfly.sh
This undoes #396, and updates the dragonfly version from 4.6.1 to 6.0.1.
This also fixes a few minor issues in the image previously:
- Brace expansion isn't quoted, so it properly expands.
- Archive files are downloaded to the temp directory, and deleted with
the image.
> Re-enable x86_64-unknown-dragonfly target.

- .github/workflows/ci.yml
- CHANGELOG.md
- docker/Dockerfile.thumbv7neon-linux-androideabi
- docker/Dockerfile.thumbv7neon-unknown-linux-gnueabihf
- src/lib.rs
Add the `thumbv7neon-linux-androideabi` and `thumbv7neon-unknown-linux-gnueabihf` targets.
Closes #254.
> Add `thumbv7neon-*` targets.

- CHANGELOG.md
- src/docker.rs
- src/file.rs
- src/lib.rs
- src/seccomp.json
Remove the use of the `--privileged` flag for Android images and instead use an seccomp permissions. The provided profile is derived from the docker documentation, with slight modifications to allow `clone` and `clone3`.
The documentation is [docker seccomp](https://docs.docker.com/engine/security/seccomp/#significant-syscalls-blocked-by-the-default-profile), which details the syscalls blocked by docker. The same is true for podman. We merely modified these settings to allow `personality` syscall, which then allows us to use our Android images.
> Limit permissions for Android images.

- README.md
- cross-dev/main.rs
- cross-dev/target_info.sh
Updated target information using the `target-info` command from `cross-dev`. Also added test detection for `cross-dev`, and fixed a bug with `powerpc64le-unknown-linux-gnu` using the wrong qemu architecture. I also removed targets for which we don't provide images, these are commented out below the table, so if we re-enable them they aren't gone entirely.
> Update README for target information.

- .github/workflows/ci.yml
- ci/test.sh
- docker/dragonfly.sh
Added `build-std` flag to CI, so for targets that support `std` but are tier 3 targets, we can use the experimental `build-std` support to ensure they build. Also patches linking on dragonfly to ensure we use `libgcc_s` instead of `libgcc_pic`, which no longer exists. We just create a symlink for that purpose.
Necessary to merge #775.
> Bug fix for dragonfly and CI tests.

- CHANGELOG.md
- src/bin/cross.rs
Forward Cargo's exit code. For example, if `cargo test` returns a non-zero exit code due to a failing test, `cross` will also return a non-zero exit code.
> Forward Cargo exit code

- src/cli.rs
- src/config.rs
- src/cross_toml.rs
- src/lib.rs
Simplifies the `config.rs` and `cross_toml.rs` to have more reusable functions, and implement logic in terms of these functions, so we can add more config options in the future. This also simplifies maintenance, since we can use 1-line logic for most config variables now.
> Simplify config internals.

- CHANGELOG.md
- src/config.rs
We currently use `build.env` over `target.$(...).env`, which means we cannot set a default value and then override it for a specific target. Given the following config file:
```toml
[build.env]
xargo = true
[target.aarch64-unknown-linux-gnu.env]
xargo = false
```
We currently would use `xargo` even on `aarch64-unknown-linux-gnu`, when we should not, and only use `xargo` for every other target.
Closes #773.
> Prefer target.env values over build.env config.

- CHANGELOG.md
- src/docker.rs
Rename `DOCKER_OPTS` to `CROSS_CONTAINER_OPTS`, and currently prefer `CROSS_CONTAINER_OPTS` to `DOCKER_OPTS`, although both are still valid.
Closes #770.
> Add `CROSS_CONTAINER_OPTS` environment variable.

- .gitmodules
- CHANGELOG.md
- README.md
- xtask/src/build_docker_image.rs
These toolchains are not automatically tested by CI, and must be built manually by the user. However, they are confirmed to build at least once, and are likely to work as-is.
> Add additional toolchains maintained by cross-rs.

- src/config.rs
- src/cross_toml.rs
Allows us to differentiate between an empty array and an array that was not provided when merging config files.
https://github.com/cross-rs/cross/pull/754#issuecomment-1156722398
Required for #754.
> Make config vectors optional.

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- docs/cross_toml.md
- src/bin/commands/images.rs
- src/cargo.rs
- src/config.rs
- src/cross_toml.rs
- src/docker/custom.rs
- src/docker/local.rs
- src/docker/mod.rs
- src/docker/shared.rs
- src/extensions.rs
- src/file.rs
- src/lib.rs
- src/rustup.rs
- xtask/src/build_docker_image.rs
- xtask/src/target_info.rs
Add optional `target.{target}.dockerfile[.file]`, `target.{target}.dockerfile.context` and `target.{target}.dockerfile.build-args` to invoke `docker/podman build` before using an image.
also adds `target.{target}.pre-build` to allow pre-building as per #565
In total, this PR allows a user to do the following:
```toml
[build]
pre-build = [
"dpkg --add-architecture $CROSS_DEB_ARCH", 
"apt-get update && apt-get --assume-yes install libssl-dev:$CROSS_DEB_ARCH"
]
[target.x86_64-unknown-linux-gnu]
dockerfile = { file = "./Dockerfile.x86_64_ssl", context = "..", build-args = { ARG1 = "foo" }}
image = "my-image:latest"
pre-build = ["echo 'Hello world!'"]
```
fixes #565
> allow specifying a dockerfile to use for a target and implement "pre-build"ing

- CHANGELOG.md
- src/lib.rs
- src/rustup.rs
This adds an environment variable `CROSS_CUSTOM_TOOLCHAIN` to disable some rustup commands.
The way to use this with `cargo-bisect-rustc` is `cargo bisect-rustc --script=./bisect.sh --target powerpc64le-unknown-linux-gnu` and the script is
```sh
#!/usr/bin/env bash
export CROSS_CUSTOM_TOOLCHAIN=1
exec cross run --target powerpc64le-unknown-linux-gnu
```
I've filed https://github.com/rust-lang/cargo-bisect-rustc/pull/159 to avoid the pitfall that was discovered when not specifying `--target`
resolves #699
> add `CROSS_CUSTOM_TOOLCHAIN` to disable automatic target component downloading

- CHANGELOG.md
- README.md
- docker/qemu.sh
The latest Qemu release contains numerous bug fixes, and other improvements, and the existing patches various issues reported in older Qemu versions. The only changes required are incrementing the Qemu version and adding ninja-build as a temporary dependency, since Qemu now uses it for the build system. However, Ubuntu 16.04, the base image for numerous dependencies we use, still ships with Python3.5, and Qemu 6.1.0 requires Python3.6+, as well as the ninja-build system. We therefore add a check to see if we have a compatible Python version, and if we do, build the last Qemu version, so our code can be fully backwards-compatible.
Closes #587.
> Update Qemu version to v6.1.0 if possible.

- Cargo.toml
- src/cargo.rs
- src/docker/engine.rs
- src/errors.rs
- src/extensions.rs
- src/file.rs
- src/rustc.rs
- src/rustup.rs
- xtask/src/hooks.rs
this makes error messages a bit better by displaying stdout/stderr if it was captured
also improves command output in verbose mode or in errors
new:
old:
> improve error messages

- src/cargo.rs
- src/docker/local.rs
- src/docker/shared.rs
- src/extensions.rs
- src/lib.rs
- src/rustc.rs
- xtask/src/hooks.rs
`rustc` and `cargo` will now use `RUSTC` and `CARGO` environment variables, respectively, if present.
> Update `rustc` and `cargo` commands to use envvars.

- .github/workflows/ci.yml
Allows wildcard selects in target names, although not in subs.
Closes #815.
> Fix wildcard and multiple selects.

- xtask/src/target_info.rs
- xtask/src/target_info.sh
These manifest in the `increment_versions` branch, but are more general since they could theoretically happen with version upgrades on the current images.
> Minor bug fixes for target-info.

- xtask/src/target_info.rs
- xtask/src/util.rs
Remove the `-it` flag from `target-info`, which can the command to not complete. Also changes `pull_image` to use `run_and_get_output` rather than `run`, which is how we should capture the output. Finally, it moves `format_repo` and `pull_image` to `util`, so they can be used by other commands.
This applies a few of the changes mentioned in #822.
> Minor xtask restructuring.

- CHANGELOG.md
- clippy.toml
- src/docker/custom.rs
- src/docker/local.rs
- src/docker/shared.rs
- src/file.rs
- src/lib.rs
- src/rustup.rs
- src/tests/toml.rs
- xtask/src/build_docker_image.rs
Adds a helper trait `ToUtf8` which converts the path to UTF-8 if possible, and if not, creates a pretty debugging representation of the path. We can then change `display()` to `to_utf8()?` and be completely correct in all cases.
On POSIX systems, this doesn't matter since paths must be UTF-8 anyway, but on Windows some paths can be WTF-8 (see rust-lang/rust#12056). Either way, this can avoid creating a copy in cases, is always correct, and is more idiomatic about what we're doing. We might not be able to handle non-UTF-8 paths currently (like ISO-8859-1 paths, which are historically very common).
So, this doesn't change ergonomics: the resulting code is as compact and correct. It also requires less copies in most cases, which should be a good thing. But most importantly, if we're mounting …
> Avoid using display on paths.

- src/docker/shared.rs
Prior to #828, we added a '/' separator before component in our makeshift `as_posix`, so the path would always become absolute, even though the actual path was relative. `as_posix` therefore handled this as a relative path, so using `project` and not `/project` as the working directory for the cross command caused commands to fail.
> Fixes regression in #828 with absolute path.

- src/bin/cross-util.rs
- xtask/src/main.rs
Changes the error message to properly report the invalid command, when an invalid command is provided.
> Fix error message with cross-util with invalid command.

- CHANGELOG.md
- src/docker/shared.rs
Ensure `cross` is similar in functionality to `cargo`, and this minimizes network traffic by applications that may copy the project but do not wish to copy compiled code.
Closes #835.
> Add a cache dir tag when creating a target directory.

- .github/workflows/ci.yml
- CHANGELOG.md
- docker/solaris.sh
Fixes the solaris targets, and re-enables them in CI. Related to #534.
> Re-enable solaris targets.

- CHANGELOG.md
- README.md
- docs/cross_toml.md
- src/config.rs
- src/cross_toml.rs
- src/lib.rs
- src/tests/toml.rs
Due to a GitHub mishap in #754, this is a new PR containing the same commits (rebased by @Emilgardis). Just for reference, it still addresses #657.
> Allow `Cargo.toml` as configuration source

- README.md
Adds support for building custom MSVC and Apple Darwin targets, and references these images in the README.
> Update external toolchains to support MSVC and Apple targets.

- .github/workflows/ci.yml
- README.md
- docker/Dockerfile.wasm32-unknown-emscripten
- xtask/src/target_info.sh
Uses a trick described in rust-lang/rust/issues#85821#issuecomment-969369677. Note that this still allows it to run, despite there seemingly being no entry point: this has no effect on the resulting code.
Related to #609. Partially fixes #839.
> Re-enable wasm32-unknown-emscripten target.

- CHANGELOG.md
- src/docker/local.rs
- src/docker/remote.rs
- src/docker/shared.rs
- src/file.rs
Removes the dependency on WSL2, and properly handles DOS-style paths, UNC paths, including those on localhost, even if Docker itself does not support them.
Closes #854.
Related to #665.
Supersedes #852.
> Remove WSLpath and implement WSL-style path.

- CHANGELOG.md
- src/config.rs
- src/cross_toml.rs
Ensure `build.env.passthrough` values are correctly parsed, and do not return `None`, and ensure that they merge as expected with `target.(...).env.passthrough` values.
> Fix parsing of config `build.env.passthrough` values.

- CHANGELOG.md
- src/cargo.rs
- src/docker/shared.rs
Provides behavior consistent with `cargo` itself, which also ignores it.
Closes #864.
Supersedes #865.
Partially reverts #808.
> Ignore the `CARGO` environment variable.

- CHANGELOG.md
- src/docker/shared.rs
Pass cargo configuration flags to docker.
Ensures the following flags are passed to docker:
- BROWSER
- CARGO_BUILD_DEP_INFO_BASEDIR
- CARGO_BUILD_INCREMENTAL
- CARGO_BUILD_JOBS
- CARGO_BUILD_RUSTDOCFLAGS
- CARGO_BUILD_RUSTFLAGS
- CARGO_CACHE_RUSTC_INFO
- CARGO_FUTURE_INCOMPAT_REPORT_FREQUENCY
- CARGO_HTTP_CAINFO
- CARGO_HTTP_CHECK_REVOKE
- CARGO_HTTP_DEBUG
- CARGO_HTTP_LOW_SPEED_LIMIT
- CARGO_HTTP_MULTIPLEXING
- CARGO_HTTP_PROXY
- CARGO_HTTP_SSL_VERSION
- CARGO_HTTP_TIMEOUT
- CARGO_HTTP_USER_AGENT
- CARGO_INCREMENTAL
- CARGO_NET_GIT_FETCH_WITH_CLI
- CARGO_NET_OFFLINE
- CARGO_NET_RETRY
- HTTP_TIMEOUT
- HTTPS_PROXY
- RUSTDOCFLAGS
- RUSTFLAGS
- TERM
These are always correct, since these configure how `cargo` behavior is
supposed to work, but don't rely on any paths on the host filesystem. …
> Pass cargo configuration flags to docker.

- xtask/src/build_docker_image.rs
- xtask/src/hooks.rs
- xtask/src/install_git_hooks.rs
- xtask/src/main.rs
- xtask/src/util.rs
Ensure general-purpose are in `xtask::util`, useful for adding more features down the line.
> Minor refactoring in xtask.

- .github/actions/cargo-install-upload-artifacts/action.yml
- .github/actions/cargo-llvm-cov/action.yml
- .github/actions/cargo-publish/action.yml
- .github/actions/post/action.yml
- .github/actions/post/main.js
- .github/codecov.yml
- .github/workflows/ci.yml
- ci/test.sh
Implements coverage via lcov artifacts and uploads them to https://app.codecov.io/gh/cross-rs/cross
> enable coverage

- ci/test.sh
Simplifies testing CI locally, without modifying the system installation.
> Update CI tests to use local cross build.

- src/bin/commands/containers.rs
- xtask/src/util.rs
Removes the requirement of an unused target from `cross-util volumes remove` and fixes the Ubuntu base testing.
> Minor bug fixes.

- CHANGELOG.md
- src/docker/shared.rs
Adds support for rootless docker, and manually overriding rootless/rootful container engines through the `CROSS_ROOTLESS_CONTAINER_ENGINE` environment variable. If not set, it will use the default mode for the container engine (rootful for docker, rootless for everything else).
```bash
cross run ...
CROSS_ROOTLESS_CONTAINER_ENGINE=auto cross run ...
CROSS_ROOTLESS_CONTAINER_ENGINE=0 cross run ...
CROSS_ROOTLESS_CONTAINER_ENGINE=1 cross run ...
```
Closes #889.
> Support rootless docker.

- CHANGELOG.md
- src/docker/local.rs
- src/docker/remote.rs
- src/docker/shared.rs
Support manual overrides of the container user namespace via the `CROSS_CONTAINER_USER_NAMESPACE` environment variable. If not set or set to `auto`, it will use the default value for the container engine (`host`). If `none` is provided, no `--userns` flag will be used. If any other value is provided, that will be the value passed to `--userns`.
This is required for using lima/nerdctl, which currently does not support the `--userns` flag.
Related to #888.
> Add manual overrides for container user namespaces.

- CHANGELOG.md
- src/docker/custom.rs
Ensures the filenames in custom docker image tags are valid docker tag
characters. This requires the following:
- lowercase ASCII letters
- digits
- a period
- 1-2 underscores
- 1 or more hyphens (dashes)
Closes #894.
> Fix tag names for custom docker images.

- CHANGELOG.md
- src/config.rs
- src/cross_toml.rs
Fix the order of values for string (as well as the pre-build vec) values when parsing from config files and environment variables.
The old behavior was:
1. Envvar build.
2. Envvar target
3. Config target
4. Config build
The new behavior is:
1. Envvar target
2. Config target
3. Envvar build.
4. Config build
Some functions were also made more general.
> Fix build/target config file ordering

- CHANGELOG.md
- src/docker/remote.rs
If using remote docker but primarily wishing to build or test your builds remotely, without caring about the generated artifacts, the time required to copy the generated artifacts over a network connection can be prohibitive.
Setting `CROSS_REMOTE_SKIP_BUILD_ARTIFACTS=1` will disable copying these build artifacts back to the host, for faster build times with remote container engines.
> Enable skipping of copying build artifacts back to host.

- CHANGELOG.md
- src/cargo.rs
- src/docker/local.rs
- src/docker/mod.rs
- src/docker/remote.rs
- src/docker/shared.rs
- src/shell.rs
Fixed `cargo metadata` failing with unstable arguments in rustflags if the default toolchain was not nightly. We also log any warnings that occurred if we cannot get metadata. Also fixed a lack of formatting in messages with remote docker support. The mount paths are also correctly processed if using docker-in-docker for mounted volumes.
Closes #901.
Closes #903.
Required for #873.
> Various bug fixes for cross.

- .github/workflows/ci.yml
- ci/shared.sh
- ci/test-bisect.sh
- ci/test-docker-in-docker.sh
- ci/test-remote.sh
- ci/test.sh
- src/bin/commands/containers.rs
- src/docker/shared.rs
Adds an an integration test for remote Docker support with and without persistent data volumes, and adds it to CI. In addition, we've added integration tests for custom toolchains using `cargo-bisect-rustc`.  Also changes the workflow  to ensure publish depends on fmt, clippy,  and cargo-deny. Fixes a bug when removing data volumes, since it does  not require a target.
> Add integration tests.

- .github/workflows/ci.yml
- CHANGELOG.md
- docker/Dockerfile.aarch64-unknown-linux-musl
- docker/Dockerfile.arm-unknown-linux-gnueabi
- docker/Dockerfile.arm-unknown-linux-gnueabihf
- docker/Dockerfile.arm-unknown-linux-musleabi
- docker/Dockerfile.arm-unknown-linux-musleabihf
- docker/Dockerfile.armv5te-unknown-linux-gnueabi
- docker/Dockerfile.armv5te-unknown-linux-musleabi
- docker/Dockerfile.armv7-unknown-linux-gnueabi
- docker/Dockerfile.armv7-unknown-linux-musleabi
- docker/Dockerfile.armv7-unknown-linux-musleabihf
- docker/Dockerfile.i586-unknown-linux-gnu
- docker/Dockerfile.i586-unknown-linux-musl
- docker/Dockerfile.i686-unknown-linux-musl
- docker/Dockerfile.mips-unknown-linux-musl
- docker/Dockerfile.mips64-unknown-linux-gnuabi64
- docker/Dockerfile.mips64-unknown-linux-muslabi64
- docker/Dockerfile.mips64el-unknown-linux-muslabi64
- docker/Dockerfile.mipsel-unknown-linux-musl
- docker/Dockerfile.x86_64-unknown-linux-musl
- docker/aarch64-linux-musl-gcc.sh
- docker/musl-symlink.sh
- docker/qemu-runner
Provide `qemu-runner` that allows native or non-native for any architecture, and install `qemu-user` binaries for x86 musl images. In addition, create symlinks so dynamically-linked binaries can be run, including for C++, with musl images.
Adding `qemu-user` runners is also useful for running dynamically-linked x86 binaries, since otherwise they may be unable to find the linked musl libc, and we cannot install it in `/lib` or `/usr/lib` due to conflicts with the system.
> Numerous bug fixes for musl and other images.

- src/lib.rs
- src/rustup.rs
Provides a warning if a docker command fails and `rust-std` is not available for the target. For example, for `x86_64-unknown-dragonfly`, the added output would be:
```bash
[cross] warning: rust-std is not available for x86_64-unknown-dragonfly
[cross] note: you may need to build components for the target via `-Z build-std=<components>` or in your cross configuration specify `target.x86_64-unknown-dragonfly.build-std`
the available components are core, std, alloc, and proc_macro
```
This is done solely if the command fails and if the target is a built-in, so we don't get misleading warnings for custom targets, and there is no overhead if the build succeeds.
Closes #94.
Closes #167.
> Better error diagnostics on targets without std.

- src/docker/shared.rs
Use create_dir_all for cargo directory.
Cargo builds all intermediate directories to `CARGO_HOME`, if not present, and hard errors if it cannot. This differs from our behavior, where we silently ignore failures and only attempt to build the current directory (ignores errors if it actually exists). If using a rootful container engine, this means we create the cargo directory and it is owned by root. This only occurs if the package has no dependencies, another fix that using `cargo metadata` solved.
An example of the hard failure shown as the following (some lines are omitted for brevity):
```bash
$ CARGO_HOME=/path/to/my/cargo cargo build
error: failed to get `cc` as a dependency of package `hellopp v0.1.0 (/home/ahuszagh/Desktop/cross/rust-cpp-hello-word)`
Caused by:
failed to create …
```
> Use create_dir_all for cargo directory.

- docker/Dockerfile.arm-unknown-linux-gnueabihf
- docker/crosstool-ng.sh
- xtask/src/build_docker_image.rs
- xtask/src/main.rs
Defaulting to verbose output pollutes the build logs during CI, which can be obscure any errors or status results. However, silencing output on local builds can make it difficult to debug issues. This checks for verbose output and the build script is running on a TTY, so we only get spinner output in those cases (IE, where the spinners actually work and are able to delete the current output line).
> Allow verbose output in ct-ng images.

- .github/workflows/ci.yml
- CHANGELOG.md
- ci/test-cross-image.sh
- docker/Dockerfile.cross
- docker/cross.sh
- xtask/src/build_docker_image.rs
- xtask/src/ci.rs
- xtask/src/util.rs
This uses the official Docker docker-in-docker image for the latest stable, and installs the latest stable Rust version internally. It uses an entrypoint to ensure cargo is on the path, and that cross is installed from the latest git (locked), which when tagged will work well with our releases. It exports the environment variable `CROSS_CONTAINER_IN_CONTAINER` so everything should work as expected.
Closes #468.
Replaces #667.
> Add dockerfile for cross.

- src/bin/commands/clean.rs
- src/bin/commands/containers.rs
- src/bin/commands/images.rs
- src/bin/cross-util.rs
- src/cargo.rs
- src/cli.rs
- src/config.rs
- src/cross_toml.rs
- src/docker/custom.rs
- src/docker/engine.rs
- src/docker/local.rs
- src/docker/mod.rs
- src/docker/remote.rs
- src/docker/shared.rs
- src/extensions.rs
- src/lib.rs
- src/rustc.rs
- src/rustup.rs
- src/shell.rs
- src/tests.rs
- src/tests/toml.rs
- xtask/src/build_docker_image.rs
- xtask/src/ci.rs
- xtask/src/crosstool.rs
- xtask/src/hooks.rs
- xtask/src/install_git_hooks.rs
- xtask/src/main.rs
- xtask/src/target_info.rs
- xtask/src/util.rs
Reduces the number of arguments to the function signatures, making the code much easier to understand, and relocates some things. For example, `docker_in_docker` is now associated with `Engine`, and now with `cli::Args`. Likewise, unstable doctests is now a part of `Environment` and not `cli::Args`. `MessageInfo` now stores mutable state (needs to clear lines) and is no longer copyable, and a single instance is created in lib and passed around everywhere as a mutable reference.
The changes with `MessageInfo` will allow us to erase lines in the future, both from `stderr` and `stdout`, which we currently don't use but will allow us to close #859.
This also fixes an issue where `-vv+` was not recognized as a valid verbose flag: `cargo` can handle 1 or more `v` characters. Also allowed …
> Structify more of the internals to simplify the implementation.

- CHANGELOG.md
- docs/cross_toml.md
- src/config.rs
- src/cross_toml.rs
- src/docker/custom.rs
- src/docker/mod.rs
- src/docker/shared.rs
> add way to run script with pre-build

- CHANGELOG.md
- src/bin/commands/clean.rs
- src/bin/commands/containers.rs
- src/bin/commands/images.rs
- src/cli.rs
- src/shell.rs
- xtask/src/build_docker_image.rs
- xtask/src/crosstool.rs
- xtask/src/hooks.rs
- xtask/src/install_git_hooks.rs
- xtask/src/target_info.rs
Use the `CARGO_TERM_VERBOSE`, `CARGO_TERM_QUIET`, and `CARGO_TERM_COLOR` environment variables for cross terminal output. This enables us to detect term settings via environment variables, which are overridden by command-line flags, which is our own behavior.
Cargo has CLI flags override environment variables, and verbose and quiet cannot be set for the same level. So if `CARGO_TERM_VERBOSE=true` and `--quiet` are used, then we use the quiet setting, but if `--verbose` and `--quiet` are used, then we print a fatal error message.
Closes #919.
> Support cargo term variables.

- .github/workflows/ci.yml
- ci/test-cross-image.sh
- ci/test-docker-in-docker.sh
same as #924
also fixes no subs on variable passthrough
> fix dind test

- .github/workflows/ci.yml
- ci/test-cross-image.sh
- ci/test-docker-in-docker.sh
> fix for real

- .changes/931.json
- CHANGELOG.md
- docker/Dockerfile.aarch64-unknown-linux-gnu
- docker/Dockerfile.arm-unknown-linux-gnueabi
- docker/Dockerfile.armv5te-unknown-linux-gnueabi
- docker/Dockerfile.armv7-unknown-linux-gnueabihf
- docker/Dockerfile.mips64-unknown-linux-gnuabi64
- docker/Dockerfile.mips64el-unknown-linux-gnuabi64
- docker/Dockerfile.mipsel-unknown-linux-gnu
- docker/Dockerfile.powerpc-unknown-linux-gnu
- docker/Dockerfile.powerpc64-unknown-linux-gnu
- docker/Dockerfile.powerpc64le-unknown-linux-gnu
- docker/Dockerfile.riscv64gc-unknown-linux-gnu
- docker/Dockerfile.s390x-unknown-linux-gnu
- docker/Dockerfile.sparc64-unknown-linux-gnu
- docker/deny-debian-packages.sh
Deny the installation of Debian packages that conflict with our cross-compiler toolchains, by using package pinning with a -1 priority to ensure they have no installation candidate.
> Deny installation of conflicting Debian packages.

- .changes/934.json
- src/docker/remote.rs
- src/docker/shared.rs
> Add support for pre-build hooks with remote docker.

- .changes/937.json
- src/cli.rs
Also adds support for absolute manifest paths.
Closes #935.
> Support Windows-style manifest paths.

- docker/Dockerfile.i686-unknown-freebsd
- docker/Dockerfile.x86_64-unknown-freebsd
- docker/freebsd-common.sh
- docker/freebsd-extras.sh
- docker/freebsd-install.sh
- docker/freebsd.sh
Uses the `path` key rather than the `version` extension to get the proper location for the package URL, which is still compressed as a tar XZ archive.
> Fix FreeBSD migration to `.pkg` extensions.

- .changes/947.json
- src/bin/commands/containers.rs
- src/docker/image.rs
- src/docker/local.rs
- src/docker/remote.rs
- src/docker/shared.rs
- src/file.rs
- src/lib.rs
Resolve symlinks for the xargo and cargo home (as well as the Nix store) prior to mounting, since they are mounted at a fixed location anyway. This is because podman mounts symlinks as root by default. We always canonicalize the paths on the host, after creating them, to ensure that any symlinks are resolved.
Say we have `/path/to/home`, and `/path/to` is a symlink but `/path/to/home` doesn't exist yet. Trying to canonicalize `/path/to/home/.xargo` will fail, and will still be a symlink if we maybe canonicalize before. First creating the directories and canonicalizing them on the host should always work.
Change the mount points from `/cargo`, `/xargo`, and `/rust` to the same paths as on the host, which avoids unnecessary recompilation when `cargo` and `cross` are intermittently used. …
> Resolve symlinks for cargo and xargo home.

- .changes/942.json
- src/cli.rs
- src/docker/local.rs
- src/docker/remote.rs
- src/docker/shared.rs
- src/file.rs
Symlinks and canonical paths can destroy assumptions about paths: say I have a file at `/tmp/path/to/file` I reference in my crate, and ask to mount `/tmp/path/to` on the container. Currently, on macOS, since `/tmp` is a symlink to `/private/tmp`, the code that expects `/tmp/path/to/file` will fail because in the container it will be mounted at `/private/tmp/path/to/file`.
In addition, this fixes `DeviceNS` parsing with drive letters (this previously didn't matter since it never occurred, due to `dunce` canonicalization). This PR also fixes a minor bug where the host root instead of the var names was passed as the environment variable (introduced in #904).
Closes #920.
> Use non-canonical paths for mount paths.

- .changes/554.json
- Cargo.lock
- Cargo.toml
- src/rustup.rs
Closes https://github.com/rust-embedded/cross/issues/536.
> Add `--force-non-host` flag.

- .changes/880.json
- .github/workflows/ci.yml
- ci/test-zig-image.sh
- docker/Dockerfile.zig
- docker/zig.sh
- docs/cross_toml.md
- src/config.rs
- src/cross_toml.rs
- src/docker/custom.rs
- src/docker/local.rs
- src/docker/provided_images.rs
- src/docker/remote.rs
- src/docker/shared.rs
- src/lib.rs
- xtask/src/codegen.rs
- xtask/src/util.rs
Uses cargo-zigbuild as a backend, and adds configuration options for zig under `[build.zig]` and `[target.(...).zig]`. If enabled, and an image override is not provided, `cross` will always use the `zig` image.
It supports custom `glibc` versions by parsing the libc portion of the target, and extracting a the libc version if present. The target, if built-in, is then the triple/libc pair, otherwise, it's just the triple.
The image does not provide runners, `bindgen` Clang args, or `pkg-config` paths, since `zig cc` does not provide the dynamic library loader (`ld-linux*.so`) required, meaning none of the binaries can be run. For `bindgen`, `zig cc` has an unusual directory structure, so there is no traditional sysroot with `usr`, `lib`, and `include` subdirectories. Finally, since we don't …
> Add a `zig cc`-based image.

- .changes/962.json
- src/docker/local.rs
Ensure that the volumes are not mounted as private, unshared volumes since we might mount with the host filesystem. This also fixes permissions issues with reading data from a mounted volume using a rootless container engine.
Fixes a bug introduced in #251.
Closes #961.
This is because the `Z` SELinux label assumes the data is not shared between containers and not being used by the host, as documented below:
> If you use selinux you can add the z or Z options to modify the selinux label of the host file or directory being mounted into the container. This affects the file or directory on the host machine itself and can have consequences outside of the scope of Docker.
> 
> - The z option indicates that the bind mount content is shared among multiple containers.
> - The Z option indicates …
> Fix SELinux labels to allow shared use.

- src/build.rs
- src/docker/shared.rs
Adds an environment variable `CROSS_SANDBOXED` that skips tests that touch the filesystem if set.
Closes #943.
>  Ignore tests that touch the filesystem if sandboxed. 

- .changes/974.json
- .github/workflows/ci.yml
- docker/Dockerfile.mips64-unknown-linux-muslabi64
- docker/mips64-linux-muslabi64-gcc.sh
Changes `mips64-unknown-linux-gnuabi64` to use a hard-float musl toolchain, rather than a soft-float one.
Closes #906.
> Change `mips64-unknown-linux-gnuabi64` to hard-float.

- .changes/989.json
- src/docker/shared.rs
This pull request fixes the nix related issues described in #260. Its super simple, I just made the nix_store match statement default to `/nix/store` if the NIX_STORE variable is not set. 
There might be some edge cases where this won't fix the problem, but should be fine for any normal NixOS installation.
> added default nix_store value

- .changes/968.json
- src/bin/cross.rs
- src/cli.rs
- src/rustc.rs
- src/rustup.rs
- src/shell.rs
- src/tests.rs
- xtask/src/build_docker_image.rs
- xtask/src/ci.rs
- xtask/src/main.rs
- xtask/src/util.rs
this will make it so rustup doesn't show verbose unless `-vv` or `-v` and `CROSS_DEBUG` is used.
> introduce verbosity levels

- docker/dragonfly.sh
- src/bin/cross.rs
> fix wrong usage of bool_from_envvar

- .changes/994.json
- ci/test-cross-image.sh
- ci/test-docker-in-docker.sh
- src/bin/commands/containers.rs
- src/docker/shared.rs
fixes #993 
```
+ /usr/local/bin/docker buildx build --label 'org.cross-rs.for-cross-target=aarch64-unknown-linux-gnu' --label 'org.cross-rs.runs-with=x86_64-unknown-linux-gnu' --label 'org.cross-rs.workspace_root=/tmp/tmp.cmePkb/workspace' --tag localhost/cross-rs/cross-custom-workspace:aarch64-unknown-linux-gnu-e570c-pre-build --build-arg 'CROSS_CMD=exit' --build-arg 'CROSS_DEB_ARCH=arm64' --file /tmp/tmp.cmePkb/workspace/target/aarch64-unknown-linux-gnu/Dockerfile.aarch64-unknown-linux-gnu-custom --output 'type=docker' /var/lib/docker/overlay2/5b7e7f3b1f39b622d2a665281973f5c1bdc2dce21f33c0bc105ceee253cfbe42/merged/tmp/tmp.cmePkb
error: unable to prepare context: path "/var/lib/docker/overlay2/5b7e7f3b1f39b622d2a665281973f5c1bdc2dce21f33c0bc105ceee253cfbe42/merged/tmp/tmp.cmePkb" not …
```
> fix path issue

- README.md
- docs/cross_toml.md
I came across this project and found possible enhancements to the documentation:
- mention that the release binaries can be used directly
- added the `pre-build` to Cross.toml `build` section, which also works
for all targets
- fixed the architecture in the arm64 example in README.md
> Fix documentation issues

- .changes/1018.json
- docker/Dockerfile.arm-unknown-linux-gnueabihf
- docker/deny-debian-packages.sh
Currently, when using `arm-unknown-linux-gnueabihf`, users frequently try to install packages for the `armhf` Debian architecture, objects which are compiled for ARMv7-A, and therefore are not compatibility with ARMv6 platforms such as the Raspberry Pi 0. This differs from the soft-float targets, where packages for the `armel` architecture are compiled for the ARMv5TE architecture, and therefore are compatible with ARMv5TE, ARMv6, and ARMv7 soft-float targets.
Deny-listing all packages for the `armhf` architecture prevents issues such as in #1017, where the use of ARMv7 system packages are linked to the binary, so the resulting binary can no longer be executed on an ARMv6 platform. This is difficult to detect until the user attempts to use the generated objects (binaries, libraries) on …
> Update deny list to all system packages for ARMv6 HF.

- .changes/1033.json
- .github/workflows/ci.yml
- ci/test-podman.sh
- src/docker/engine.rs
- xtask/src/build_docker_image.rs
Ensures that docker and nerdctl, which support the custom `--output` and `--cache-from` flags use them, while podman and unknown container engines use the strict, minimal subset podman supports. This is because podman only supports a registry/repository, without a tag, for `--cache-from`, which means it synchronizes poorly with our target subs, like `centos`. Therefore, unless unsupported, we should always use the features available for our container engine.
This also fixes the `--pull` flag on nerdctl, which is unsupported. Engines without BuildKit extensions by default, such as nerdctl, now do not use `buildx` unless explicitly enabled with `CROSS_CONTAINER_ENGINE_NO_BUILDKIT=0`.
Closes #1031.
> Fix image build errors with podman and nerdctl.

- .changes/1039.json
- src/docker/shared.rs
This allows other storage engines, such as `overlay` and `fuse-overlayfs` to be used with `CROSS_CONTAINER_IN_CONTAINER`. Any overlay filesystem can be supported, and this has been tested with both `overlay` and `overlay2`.
> Add support for other overlay filesystems.

- .github/actions/cargo-install-upload-artifacts/action.yml
- .github/actions/cargo-publish/action.yml
- .github/actions/setup-rust/action.yml
- .github/actions/setup-rust/rust.json
- .github/workflows/ci.yml
- src/lib.rs
This essentially removes all actions-rs actions and replaces it with what is needed.
Reason for this is due to actions-rs being seemingly unmaintained
> remove actions-rs

- .changes/1028.json
- docker/Dockerfile.armv5te-unknown-linux-musleabi
- docker/Dockerfile.i686-unknown-freebsd
- docker/Dockerfile.mips-unknown-linux-musl
- docker/Dockerfile.mips64-unknown-linux-muslabi64
- docker/Dockerfile.mips64el-unknown-linux-muslabi64
- docker/Dockerfile.mipsel-unknown-linux-musl
- docker/Dockerfile.x86_64-unknown-freebsd
- docker/aarch64-linux-musl-gcc.sh
- docker/arm-linux-musleabi-gcc.sh
- docker/i686-unknown-freebsd12-gcc.sh
- docker/mips64-linux-musl-gcc.sh
- docker/mips64el-linux-musl-gcc.sh
- docker/x86_64-unknown-freebsd12-gcc.sh
- src/docker/local.rs
- src/docker/remote.rs
- src/docker/shared.rs
- src/lib.rs
- targets.toml
- Fixes linking to libgcc for `armv5te-unknown-linux-musleabi`.
- Adds C++ support for FreeBSD targets by linking to `libstdc++`.
- Tests dynamic library support for Android targets in CI.
- Tests C++ support for `mips64el-unknown-linux-muslabi64` in CI.
- Convert `mips64el-unknown-linux-muslabi64` to a hard-float toolchain to match the rust target.
- Convert `mips64el-unknown-linux-muslabi64` to use the `mips64r2` architecture.
- Convert `mips-unknown-linux-musl` and `mipsel-unknown-linux-musl` to use the `mips32r2` architecture, identical to the rust targets.
- Document whether MIPS musl targets are hard or soft float.
> Fix tests, linkers, and specifications for various targets.

- docker/Dockerfile.aarch64-unknown-linux-musl
- docker/Dockerfile.armv5te-unknown-linux-musleabi
- docker/Dockerfile.mips64-unknown-linux-muslabi64
- docker/Dockerfile.mips64el-unknown-linux-muslabi64
- docker/aarch64-linux-musl-gcc.sh
- docker/arm-linux-musleabi-gcc.sh
- docker/mips64-linux-musl-gcc.sh
- docker/mips64el-linux-musl-gcc.sh
- docker/rustc_info.sh
Fixes an issue where `CROSS_RUSTC_MINOR_VERSION` is not present when using older versions of cross but newer images. This only uses the fallback if the minor version is not provided as an environment variable by cross itself.
> Provide fallback for rustc version when envvars not present.

- .changes/1049.json
- src/cli.rs
Resolves #1048.
Stop parsing arguments to `cross run` after `--`, but still add them to `args.all` so they will be passed to the program being run.
> Stop parsing arguments to `cross run` after `--`.

- src/bin/commands/images.rs
- src/docker/custom.rs
- src/docker/engine.rs
touches on #1055
```
❯ cross build --target x86_64-unknown-linux-gnu
unknown flag: --label
See 'docker buildx build --help'.
Error: 
0: could not run container
1: when building custom image
2: when pre-building
3: `docker buildx build --platform linux/amd64 --labela 'org.cross-rs.for-cross-target=x86_64-unknown-linux-gnu' --label 'org.cross-rs.runs-with=x86_64-unknown-linux-gnu' --label 'org.cross-rs.workspace_root=/Users/emil/workspace/cross' --tag localhost/cross-rs/cross-custom-cross:x86_64-unknown-linux-gnu-b0dac-pre-build --build-arg 'CROSS_CMD=hello world' --build-arg 'CROSS_DEB_ARCH=amd64' --file /Users/emil/workspace/cross/target/x86_64-unknown-linux-gnu/Dockerfile.x86_64-unknown-linux-gnu-custom --output 'type=docker' /Users/emil/workspace/cross` failed with exit status: 125 …
```
> suggest that buildx needs to be available

- docker/aarch64-linux-gnu-glibc.sh
- docker/lib.sh
- docker/qemu.sh
Fixes CentOS builds being ~10x slower with certain configurations, where `LimitNOFILE=infinity`. This sets the ulimit for open file descriptors manually, which fixes the issue. See the upstream issue https://github.com/docker/buildx/issues/379.
> Workaround for slow CentOS builds depending on the ulimit.

- .changes/1054.json
- src/bin/commands/containers.rs
- src/docker/local.rs
- src/docker/remote.rs
- src/docker/shared.rs
This changes the unique container IDs to be based off the toolchain ID, the host target name, the hash of the current working directory, the system time. This means it will be fully unique at the millisecond resolution. This also separated package and toolchain directories. Toolchain directories are the only ones required when creating persistent data volumes, while running cross requires both. There are no backwards incompatible changes, since the persistent data volumes stay the same.
Closes #1045.
> Allow Persistent Data Volume to be Created Outside of Package

- src/docker/local.rs
- src/docker/remote.rs
- src/docker/shared.rs
> Warn when mounted volume likely uses a path rather than an environment variable.

- src/bin/commands/containers.rs
- src/docker/local.rs
- src/docker/mod.rs
- src/docker/remote.rs
- src/docker/shared.rs
- src/errors.rs
Upon receiving a termination signal, ensuring any spawned containers are also terminated. This is required since we intentional do not attach stdint to the container. This means, however, that interrupts such as Ctrl+C did not stop the build process. Likewise, termination signals such as SIGTERM merely exited cross, and did not terminate the container.
This also refactors the global container state to store whether the container exists and current logic to terminate the container if it exists. By coupling the two, it simplifies safe handling and modification of this global state. Since we have a signal handler, these functions may be called asynchronously, therefore any global state may be modified, rendering the current state invalid if not appropriately guarded. Coupling the two ensures …
> Terminate child containers on program termination.

- src/bin/commands/containers.rs
- src/bin/commands/images.rs
- src/docker/custom.rs
- src/docker/local.rs
- src/docker/remote.rs
- src/docker/shared.rs
- src/errors.rs
- src/lib.rs
- xtask/src/build_docker_image.rs
- xtask/src/target_info.rs
- xtask/src/util.rs
This fixes copying files into a directory inside a docker data volume, where previously we copied the entire temp directory into the volume itself. This meant that `tmp.tmpLkX8M3` would be copied to `"${volume}/tmp.tmpLkX8M3"`, rather than its contents being copied into `"${volume}"`. This also contains numerous other bugs fixes and changes internally, which have been submitted each as separate commits.
This fixes a regression in #1054 to re-enable fingerprinting to work, since previously the fingerprint file name was based off the container name. Since #1054 changes the container names to rely on the system time, this ensures the fingerprints are specific for only the toolchain and the path of directory.
This also simplifies the internals of the docker module substantially. Most free …
> Fix persistent data volumes with remote cross.

- .changes/1078.json
- src/docker/custom.rs
> Fix custom image names for images with a trailing '-' character.

- docker/Dockerfile.aarch64-linux-android
Remove typo `t` from sysroot definition.
> Fix typo in aarch64-linux-android Dockerfile

- .gitattributes
- ci/test-remote.sh
- src/bin/commands/containers.rs
- src/bin/commands/images.rs
- src/bin/cross.rs
- src/docker/remote.rs
- src/docker/shared.rs
- src/extensions.rs
- src/lib.rs
- src/shell.rs
- don't hide hostname querying in verbose
- output cross images as json
- associate `CROSS_DEBUG` with `MessageInfo`
- track caller when doing debug or error prints from `MessageInfo` and print the line it comes from
> Improve error diagnostics and other changes

- .changes/1085.json
- src/docker/shared.rs
- src/lib.rs
- src/rustc.rs
- src/tests.rs
Avoids checking for installed toolchains, and also prevents renaming the sysroot based on the toolchain full name, since this may be in a directory completely different than the target name.
> Fixes custom toolchain support without rustup.

- .changes/1063.json
- ci/test.sh
- docker/musl-symlink.sh
- docker/musl.sh
- targets.toml
Change behavior to use static-pie linkage by default (consistent with Alpine's behavior for pure Rust packages as well as those with external C dependencies), and fix musl targets with C++ dependencies by forcing static-pie linkage to standard libraries.
Closes #902.
> Fix linkage and C++ support for musl targets.

- .changes/1105.json
- docker/Dockerfile.i686-unknown-freebsd
- docker/Dockerfile.sparcv9-sun-solaris
- docker/Dockerfile.thumbv6m-none-eabi
- docker/Dockerfile.thumbv7em-none-eabi
- docker/Dockerfile.thumbv7em-none-eabihf
- docker/Dockerfile.thumbv7m-none-eabi
- docker/Dockerfile.x86_64-sun-solaris
- docker/Dockerfile.x86_64-unknown-dragonfly
- docker/Dockerfile.x86_64-unknown-freebsd
- docker/Dockerfile.x86_64-unknown-netbsd
> Explicitly prefer `-ar` to `-gcc-ar`.

- .changes/1123.json
- .changes/591-1095.json
- docker/Dockerfile.i686-pc-windows-gnu
- docker/Dockerfile.x86_64-pc-windows-gnu
- docker/wine.sh
This changes from using WIN32 threads to POSIX threads when linking. MinGW (when using `libstdc++`) doesn't support C11 and C++11 threading support with WIN32 threads. This PR also makes WINE builds more resilient. Note that this will not affect any multi-threaded Rust code, which uses the Win32 API, calling `CreateThread` and `WaitForSingleObject` directly.
Closes #1122.
> Use MinGW GCC with POSIX thread support when linking.

- .github/actions/cargo-install-upload-artifacts/action.yml
- .github/actions/cargo-llvm-cov/action.yml
- .github/actions/cargo-publish/action.yml
- .github/actions/post/main.js
- .github/actions/setup-rust/action.yml
- .github/workflows/changelog.yml
- .github/workflows/ci.yml
- .github/workflows/weekly.yml
- xtask/src/build_docker_image.rs
- xtask/src/ci.rs
- xtask/src/ci/target_matrix.rs
- xtask/src/util.rs
This fixes most deprecation warnings from GitHub Actions.
Changes:
- CI: Replace deprecated `::set-output` command
- CI: Replace deprecated `::save-state` command
- CI: Bump [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain) from `v1` to `master`
- CI: Replace [`Ana06/get-changed-files`](https://github.com/Ana06/get-changed-files) by [`tj-actions/changed-files`](https://github.com/tj-actions/changed-files)
Fixes #1074
> CI: Fix most deprecation warnings from GitHub Actions

- .github/workflows/changelog.yml
`readarray` is supposed to be used with actual files, so replace it with `read` and also configure bash's internal field separator (IFS) to use the `;` character as the delimiter.
This allows for the list of files to be properly split.
> CI: Fix changelog check

- Cargo.lock
- Cargo.toml
- deny.toml
- src/shell.rs
Although this doesn't affect cross (since we do not use custom allocators), this address [rustsec-1457](https://github.com/rustsec/advisory-db/issues/1457).
> Replace atty with is-terminal.

- .changes/1160.json
- src/lib.rs
> Don't warn when toolchain version is explicitly provided.

- .github/workflows/weekly.yml
- xtask/src/ci.rs
- xtask/src/ci/target_matrix.rs
since the maximum timeout for workflows is not enough, we need to use the same strategy as our normal ci flow
also adds the ability to filter targets to run
this pr also pushes the results so that the cache is renewed, making the images not stagnate
> improve weekly checks and push the resulting images

- .changes/1057.json
- ci/shared.sh
- ci/test-bisect.sh
- ci/test-foreign-toolchain.sh
- ci/test-podman.sh
- ci/test-remote.sh
- ci/test-zig-image.sh
- ci/test.sh
- src/docker/local.rs
- src/file.rs
Fixes mount paths outside of the workspace mount directory on Windows and those provided as a WSL path. This also adds unittests for Windows outside of WSL2.
Closes #1145.
Closes #1156.
> Fix mount paths on Windows.

- .changes/1166.json
- docker/freebsd.sh
libc 0.2.138 added memstat_* functions, but the build with cross fails because the build image does not contain the corresponding library. See https://github.com/rust-lang/libc/issues/3025 for more context. See also https://github.com/rust-lang/rust/pull/105222 which is the same fix to rust-lang/rust's build image.
> freebsd: include memstat in build image

- README.md
Remove the duplicated entry `mips-unknown-linux-musl` in the README.
> Remove duplicated entry from README

- src/docker/custom.rs
The original bug fix solved the problem of a image name ending in a single `-` character (which docker doesn't permit). However, docker also doesn't permit names ending in a `.`, so we need to handle that case too.
Also, removing just the last char is insufficient, as names may end up ending with multiple consecutive `-` or `.` characters, so we need to loop until they're all gone.
> Bugfix: custom image tag can't end with neither a `-` nor `.`

- .changes/1183.json
- src/cross_toml.rs
- src/docker/custom.rs
- src/docker/image.rs
- src/lib.rs
- src/tests/toml.rs
`pre-build = "file"` and `image.toolchain` had a bad serialization, this fixes that
Closes #1182
> Fix error when using certain config values in Cargo.toml

- .changes/1199.json
- src/docker/remote.rs
> Bugfix: use current target_dir path when copying build artifacts back

- .changes/1207.json
- src/docker/remote.rs
> Copy remote directories correctly

- .changes/1246.json
- src/lib.rs
This makes cross usable with other bare metal targets (e.g. mips, riscv) with a custom image. Without this change, cross will always fallback to host cargo because `needs_docker` returns `false`.
---
Thumb is not necessarily bare metal, it can also be windows/linux/android:
```
thumbv7a-pc-windows-msvc
thumbv7a-uwp-windows-msvc
thumbv7neon-linux-androideabi
thumbv7neon-unknown-linux-gnueabihf
thumbv7neon-unknown-linux-musleabihf
```
But thumb bare metal targets are `-none-eabi` or `-none-eabihf`.
> fix is_bare_metal

- .changes/1248.json
- xtask/src/build_docker_image.rs
Additional Dockerfiles for some of targets (f.e MacOS) require building docker images from [cross-toolchains](https://github.com/cross-rs/cross-toolchains) repositoriy, which is supported by `build-docker-image` command.
When running build-docker-image on CI environments, such as Github Actions, the process could be made greatly faster if cache from previous build is stored. The official support of buildx system includes f.e. possibility to use Github Actions Cache directly - https://docs.docker.com/build/cache/backends/gha/ , or for other CI systems it is also possible to use local cache in folder - https://docs.docker.com/build/cache/backends/local/ . However, such configurations require passing `--cache-to` and `--cache-from` options to docker build command, which is currently not …
> Customize `--cache-to`, `--cache-from` options for `build-docker-image`

- README.md
Based on https://github.com/cross-rs/cross/issues/680, it is stated to add `ghcr.io/cross-rs/...` before the image tag. However, this is not stated in the README.md file, resulting in the error "docker login" being needed. 
With this update, the problem is fixed.
> Update README.md for centos image target notes [5] and [7]

- src/docker/image.rs
Fix ImagePlatform resolution for `Aarch64UnknownLinuxMusl` to set the `architecture` to `Architecture::Arm64`.
This fixes #1253
> Fix ImagePlatform resolution

- .changes/1260.json
- src/docker/local.rs
This PR adds SELinux labels to volume mounts on other engines than Podman.
Fixes #756
> Podman doesn't support SELinux labels

- .changes/1325.json
- src/docker/custom.rs
- src/docker/shared.rs
Closes https://github.com/cross-rs/cross/issues/1324.
> create CACHEDIR.TAG during custom docker build

- .changes/1271.json
- .github/ISSUE_TEMPLATE/b_issue_report.yml
- docker/Dockerfile.aarch64-unknown-freebsd
- docker/freebsd-common.sh
- docker/freebsd-extras.sh
- src/docker/image.rs
- src/docker/provided_images.rs
- src/lib.rs
- targets.toml
👋🏾 
Thanks for Cross, we've been using it at the pact-foundation to build cross platform targets, and I've gone through the target list and attempted to build for everything I can. See [PR here](https://github.com/pact-foundation/pact-reference/pull/276)
I've managed to build for freebsd in a parallels vm on a mac m1 pro, but makes sense to try and apply that to a Docker image.
Relates to https://github.com/cross-rs/cross/issues/975
Still requires testing but thought I would drop it here for others to have a look at / test / try out
> feat: add aarch64-unknown-freebsd image

- .changes/1333.json
- .github/workflows/ci.yml
- README.md
- docker/crosstool-config/arm-unknown-linux-gnueabihf.config
- docker/crosstool-ng.sh
- xtask/src/ci/target_matrix.rs
> bump arm-unknown-linux-gnueabihf to glibc 2.31

- .changes/1348.json
- docker/netbsd.sh
> add execinfo for netbsd

- .changes/1330-1349.json
- docker/zig.sh
to solve this problem: https://github.com/rust-cross/cargo-zigbuild/issues/151
> use cargo-zigbuild 0.17.3 instead of 0.17.2

- src/docker/engine.rs
- src/docker/local.rs
- src/docker/remote.rs
- src/docker/shared.rs
I recently encountered #1098 and propose an iteration on the fix in #890
This patch adds a last minute check that looks up the current builder endpoint. This may be seen as a costly operation however, as mentioned in #889
Here's the output of `docker builder inspect` on my rootless install:
```
Name:          rootless
Driver:        docker
Last Activity: 2023-12-03 02:04:14 +0000 UTC
Nodes:
Name:      rootless
Endpoint:  rootless  # <= THIS HERE
Status:    running
Buildkit:  v0.11.7+d3e6c1360f6e
Platforms: linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/amd64/v4, linux/386
Labels:
org.mobyproject.buildkit.worker.moby.host-gateway-ip: 172.17.0.1
```
> feat(rootless): help detection with execv check "is current builder rootless?"

- docker/linux-image.sh
Fixes 
```
#21 22.27 Get:2 http://ftp.ports.debian.org/debian-ports unreleased InRelease [50.3 kB]
#21 22.34 Err:1 http://ftp.ports.debian.org/debian-ports unstable InRelease
#21 22.34   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B523E5F3FC4E5F2C NO_PUBKEY 8D69674688B6CB36
#21 22.42 Err:2 http://ftp.ports.debian.org/debian-ports unreleased InRelease
#21 22.42   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B523E5F3FC4E5F2C NO_PUBKEY 8D69674688B6CB36
#21 22.43 Reading package lists...
#21 22.44 W: GPG error: http://ftp.ports.debian.org/debian-ports unstable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B523E5F3FC4E5F2C …
```
> Resolve build container errors

- .changes/1399.json
- .gitignore
- CHANGELOG.md
- docker/linux-image.sh
As promised here's the fixed `linux-image.sh` script.
As outlined in #1399 this pr fixes:
* Missing gpg key 8D69674688B6CB36 (Debian Ports Archive Automatic Signing Key (2024) <ftpmaster@ports-master.debian.org>)
* The binaries and busybox might also be installed into `/usr/bin/` instead of `/bin`.
* The kernel modules might also installed into `/usr/lib/modules` instead of `/lib/modules`.
* The kernel modules might be compressed with `xz` and end with `*.ko.xz` instead of just `*.ko`
The first commit adds some vim special files to `.gitignore` and in the second commit the script was formatted with `shfmt` with standard settings and some minor issues from `shellcheck` were fixed.
The third commit fixes the actual issues. Not sure if you wanna keep the first two commits but they made …
> Fix `docker/linux-image.sh` script

- targets.toml
This was missed in https://github.com/cross-rs/cross/pull/1394 somehow
> make `mips-unknown-linux-musl` and `mipsel-unknown-linux-musl` use build-std in ci

- .changes/1390.json
- docker/Dockerfile.aarch64-unknown-freebsd
- docker/Dockerfile.i686-unknown-freebsd
- docker/Dockerfile.x86_64-unknown-freebsd
- docker/freebsd-common.sh
- docker/freebsd-fetch-best-mirror.sh
- docker/freebsd-install-package.sh
- docker/freebsd-setup-packagesite.sh
- docker/freebsd.sh
Rerolling #1401 following GH closing it on push mistake - :sigh:
> Switch to FreeBSD 13.2 

- .github/workflows/changelog.yml
- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- clippy.toml
- src/docker/image.rs
- src/docker/shared.rs
- src/errors.rs
- src/shell.rs
- xtask/src/build_docker_image.rs
- xtask/src/changelog.rs
- xtask/src/hooks.rs
- xtask/src/main.rs
- xtask/src/util.rs
- revamp changelog commands
- always prefix with `#` on pr
- validate everything when run locally with no args
- never display env section
- begone syn 1
- make summation of reports actually look nice, and implement it in changelog validate
> some xtask changes

- docker/musl.sh
This was removed in #1346 for unknown reasons. I'm adding it back in.
> Add GCC_CONFIG option to enable default PIE

- docs/custom_images.md
Points the broken links in [docs/custom_images]( https://github.com/cross-rs/cross/blob/main/docs/custom_images.md#custom-dockerfile) to the renamed file.
> Fix broken links to config_file in custom images docs

- .changes/1465.json
- .github/ISSUE_TEMPLATE/b_issue_report.yml
- README.md
- crosstool-ng/loongarch64-unknown-linux-gnu.config.in
- docker/Dockerfile.loongarch64-unknown-linux-gnu
- docker/crosstool-config/loongarch64-unknown-linux-gnu.config
- docker/crosstool-ng.sh
- src/docker/image.rs
- src/docker/provided_images.rs
- targets.toml
This PR introduces a basic build-only image for the `loongarch64-unknown-linux-gnu` target. The Debian port for LoongArch is currently underway, and we anticipate further developments in the near future.
Close #1404
> feat: add loongarch64-unknown-linux-gnu image

- .changes/1466.json
- README.md
- docker/Dockerfile.loongarch64-unknown-linux-gnu
- docker/qemu.sh
- targets.toml
Even though the Debian/LoongArch port is still in progress, qemu-user is now available. This PR upgrades qemu to version `8.2.2` and incorporates qemu-user runners for the `loongarch64-unknown-linux-gnu` target.
Close #1467
> Upgrade qemu and integrate qemu-user runners for loongarch64

- .changes/1481.json
- src/docker/shared.rs
When environment variable pass-through is used, a warning is displayed if the name of the variable contains a number and the value is taken from the host. For example:
```
[cross] warning: got environment variable of "MY_VAR_AES256" which is not a valid environment variable name. the proper syntax is `passthrough = ["ENVVAR=value"]`
```
The variable is still passed onto the cross container with the value from the host, but the warning is misleading.
> Allow environment variables to contain numbers

- .changes/1458.json
- docker/Dockerfile.aarch64-unknown-linux-gnu
- docker/Dockerfile.arm-unknown-linux-gnueabi
- docker/Dockerfile.armv5te-unknown-linux-gnueabi
- docker/Dockerfile.armv7-unknown-linux-gnueabi
- docker/Dockerfile.armv7-unknown-linux-gnueabihf
- docker/Dockerfile.i586-unknown-linux-gnu
- docker/Dockerfile.i686-unknown-linux-gnu
- docker/Dockerfile.mips-unknown-linux-gnu
- docker/Dockerfile.mips64-unknown-linux-gnuabi64
- docker/Dockerfile.mips64el-unknown-linux-gnuabi64
- docker/Dockerfile.mipsel-unknown-linux-gnu
- docker/Dockerfile.powerpc-unknown-linux-gnu
- docker/Dockerfile.powerpc64-unknown-linux-gnu
- docker/Dockerfile.powerpc64le-unknown-linux-gnu
- docker/Dockerfile.riscv64gc-unknown-linux-gnu
- docker/Dockerfile.s390x-unknown-linux-gnu
- docker/Dockerfile.sparc64-unknown-linux-gnu
- docker/Dockerfile.thumbv7neon-unknown-linux-gnueabihf
- docker/Dockerfile.x86_64-pc-windows-gnu
- docker/Dockerfile.x86_64-unknown-linux-gnu
- docker/aarch64-linux-gnu-glibc.sh
- docker/common.sh
- docker/dragonfly.sh
- docker/freebsd.sh
- docker/illumos.sh
- docker/musl.sh
- docker/netbsd.sh
- docker/solaris.sh
Add gfortran support for all docker except target of `*-none*` and `*-andriod*`.
Close #1457
> docker: Add gfortran support

- .github/actions/cargo-llvm-cov/action.yml
Fixes the `cargo-llvm-cov` action breaking on Windows runners since `dtolnay/rust-toolchain` started setting `CARGO_HOME`.
I pinned the `cargo-llvm-cov` version to `0.5.3`, the one currently used, to change as few things as possible.
No changelog entry included, since this only affects CI.
> Update `taiki-e/install-action` to `v2`

- .changes/1483.json
- src/docker/local.rs
- src/docker/shared.rs
Currently, `MountFinder` is used for almost all paths, rather than only for the host path in bind/volume mounts.
Because of this, `docker build` invocations use the wrong working directory (`/var/lib/docker/.../workdir-path` instead of `/workdir-path`), causing failures for builds that use `pre-build` with a relative file path, and `docker run` invocations use incorrect `-v` arguments (e.g. `/var/lib/docker/.../toolchain-dir:/var/lib/docker/.../toolchain-dir` instead of `/var/lib/docker/.../toolchain-dir:/toolchain-dir`).
This PR fixes those issues by only using `find_path` and `find_mount_path` when necessary.
> Fix paths when using `CROSS_CONTAINER_IN_CONTAINER`

- .changes/1485.json
- src/docker/shared.rs
> Use `/proc/self/mountinfo` as a fallback for `docker inspect` if using `HOSTNAME` fails

- .changes/1488.json
- docs/config_file.md
- src/config.rs
- src/cross_toml.rs
- src/lib.rs
Closes #896.
This is technically a breaking change because arbitrary strings passed to the `CROSS_BUILD_STD` environment variable (e.g. `yes`) are now no longer parsed as truthy values, but rather as a single crate name (or multiple, if containing commas) to pass to `-Zbuild-std` (resulting in e.g. `-Zbuild-std=yes`, which is invalid).
Behaviour remains the same when `CROSS_BUILD_STD` is set to `true`, `false`, or a number that fits in an `i32`.
> Allow `build-std` to take an array of crate names

- .changes/1491.json
- Cargo.toml
- docs/config_file.md
- src/bin/commands/run.rs
- src/config.rs
- src/cross_toml.rs
- src/docker/image.rs
- src/docker/mod.rs
- src/docker/shared.rs
- src/lib.rs
Closes #1169.
Also supports specifying only a hash (`@sha256:...`) or subtarget (`-centos`).
> Allow specifying only a tag or subtarget for images in config

- .changes/1494.json
- src/docker/shared.rs
Currently, `image` always takes precedence over `zig.image`.
This change makes it so `image` doesn't get used when zig is enabled, even if `zig.image` is unset (and vice versa).
This is a breaking change.
> Fix `zig.image` precedence

- .changes/1525.json
- README.md
- ci/test.sh
- docker/Dockerfile.riscv64gc-unknown-linux-gnu
- docker/lib.sh
- docker/linux-image.sh
- docker/qemu.sh
- xtask/src/target_info.sh
> Fix riscv64gc-unknown-linux-gnu target

- .changes/1540.json
- README.md
- docker/Dockerfile.loongarch64-unknown-linux-gnu
- docker/crosstool-config/loongarch64-unknown-linux-gnu.config
- docker/crosstool-ng.sh
> Upgrade crosstool for loongarch64-unknown-linux-gnu target

- .github/actions/post/action.yml
Blog post: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
> ci: use node20 in post action

- src/lib.rs
After following the installation step at https://github.com/cross-rs/cross?tab=readme-ov-file#installation 
I see the following output when running the commands:
```
❯ ccrossbuild --target aarch64-unknown-linux-gnu
[src/lib.rs:944:30] workspace_metadata.get("cross") = None
``` 
which looks like a leftover.
> Remove a dbg!

- .changes/1623.json
- deny.toml
- src/lib.rs
> don't look at `package.metadata.cross` when the package isn't part of the current workspace

- .changes/1625.json
- docker/Dockerfile.loongarch64-unknown-linux-gnu
- docker/Dockerfile.loongarch64-unknown-linux-musl
- docker/crosstool-ng.sh
Bump ct-ng to [1.27.0](https://github.com/crosstool-ng/crosstool-ng/releases/tag/crosstool-ng-1.27.0).
> Bump ct-ng to 1.27.0

- .changes/1641.json
- .changes/2025-03-08.json
- docker/illumos.sh
- docker/solaris.sh
> Update binutils to 2.38 on illumos and solaris

- .changes/1651.json
- docker/Dockerfile.x86_64-unknown-illumos
Hello! The Docker image for `x86_64-unknown-illumos` specifies a `BINDGEN_EXTRA_CLANG_ARGS` variable for `sparcv9_sun_solaris`. I noticed while working on this PR: https://github.com/aws/aws-lc-rs/pull/709
This commit updates the name of the variable to match the intended target.
> Fix illumos BINDGEN_EXTRA_CLANG_ARGS

- .changes/1664.json
- .github/ISSUE_TEMPLATE/b_issue_report.yml
- README.md
- docker/Dockerfile.riscv64gc-unknown-linux-musl
- docker/crosstool-config/riscv64gc-unknown-linux-musl.config
- src/docker/provided_images.rs
- targets.toml
Close #1197
* * *
Only use crosstools-ng
If use [musl-cross-make](https://github.com/richfelker/musl-cross-make), `binutils` version is to low too `ld` cannot link in riscv
I test [musl.cc](http://musl.cc/) [riscv64-linux-musl-cross.tgz](http://musl.cc/riscv64-linux-musl-cross.tgz), It's ok `binutils: 2.37`, `ld` can link, It's working
But, `musl-cross-make` is only support `binutils: 2.33.1`, `binutils: 2.33.2` is big changed, The patch is unavailable, migration this patch is very complex (a lot of conflict). BTW: These patches have nothing to do with riscv
> feat: add riscv64gc-unknown-linux-musl image

- docker/Dockerfile.arm-unknown-linux-gnueabihf
- docker/Dockerfile.loongarch64-unknown-linux-gnu
- docker/Dockerfile.loongarch64-unknown-linux-musl
LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 20) https://docs.docker.com/reference/build-checks/legacy-key-value-format/
> fix Dockerfile warn LegacyKeyValueFormat ENV key value => ENV key=value

- docker/Dockerfile.aarch64-unknown-linux-musl
- docker/Dockerfile.arm-unknown-linux-musleabi
- docker/Dockerfile.arm-unknown-linux-musleabihf
- docker/Dockerfile.armv5te-unknown-linux-musleabi
- docker/Dockerfile.armv7-unknown-linux-musleabi
- docker/Dockerfile.armv7-unknown-linux-musleabihf
- docker/Dockerfile.i586-unknown-linux-musl
- docker/Dockerfile.i686-unknown-linux-musl
- docker/Dockerfile.loongarch64-unknown-linux-musl
- docker/Dockerfile.mips-unknown-linux-musl
- docker/Dockerfile.mips64-unknown-linux-muslabi64
- docker/Dockerfile.mips64el-unknown-linux-muslabi64
- docker/Dockerfile.mipsel-unknown-linux-musl
- docker/Dockerfile.riscv64gc-unknown-linux-musl
- docker/Dockerfile.x86_64-unknown-linux-musl
- docker/lib.sh
- docker/musl.sh
- docker/tidyup.sh
Here is a proof of concept patchset which reduces the size of the musl images from ~2.4G to ~1.2G, on the two architectures I tried (x86_64 and aarch64).
Using aarch64 as a primary testbed, I got these results:
* Baseline (edge): image size 2.39G (794M gzipped)
* Patch 1 (strip the binaries in musl.sh): 1.55G
* Add patch 2 (flatten the output image): 1.31G
* Add patch 3 (additional tidyup script): 1.22G (348M gzipped).
A space/bandwidth saving of 47% uncompressed, 56% compressed.
I've tested the result with my use cases (x86_64 and aarch64). The crate I am cross-compiling depends on `ring` which has a C component.
There is almost certainly more squeezing that could be done, but the Law of Diminishing Returns kicks in somewhere. For example, I spotted copies of identical binaries in …
> [RFC] Shrink musl docker image size by ~50%

- .changes/1674.json
- README.md
- docker/freebsd-extras.sh
- docker/freebsd-install.sh
- docker/freebsd.sh
- xtask/src/target_info.sh
Currently, this patch is tested by built the docker image but haven't test the build of any application upon the docker image.
When I use cross to build application, it will create the following Dockerfile in the target directory:
```
FROM ghcr.io/cross-rs/x86_64-unknown-freebsd:main
ARG CROSS_DEB_ARCH=
ARG CROSS_CMD
RUN eval "${CROSS_CMD}"
```
I try to replace the "FROM" sentence to my local build image but when `cross build` is executed, it will recover to ghcr.io again.
FreeBSD change the compress algorithm of the packagesite to zstd. Also it change the download filename.
Besides fixing the download issue, I update the gcc version to 13
> freebsd: fix image build

- .github/actions/setup-rust/action.yml
- .github/workflows/ci.yml
- docker/Dockerfile.armv5te-unknown-linux-musleabi
- docker/Dockerfile.native.centos
- docker/aarch64-linux-gnu-glibc.sh
- docker/cmake.sh
- docker/freebsd.sh
- docker/lib.sh
- docker/linux-image.sh
- docker/netbsd.sh
- docker/qemu.sh
- src/bin/commands/images.rs
- src/docker/shared.rs
- targets.toml
This PR should fix most issues encountered when building docker images.
As a reminder of the docker build images currently failing:
- [target (armv5te-unknown-linux-musleabi,ubuntu-latest)](https://github.com/alexis-opolka/cross/actions/runs/14738556356/job/41370886350#logs) => Dockerfile.armv5te-unknown-linux-musleabi
- [target (s390x-unknown-linux-gnu,ubuntu-latest)](https://github.com/alexis-opolka/cross/actions/runs/14738556356/job/41370895370#logs) => Failing before the docker image build
> Fixes issues with the docker images build

- .changes/1681.json
- src/rustup.rs
Fixes #1678
```shell
$ rustup --quiet toolchain list
stable-aarch64-apple-darwin (active, default)
```
```shell
$ rustup toolchain list --quiet
stable-aarch64-apple-darwin
```
> fix(rustup): toolchain list --quiet

- src/config.rs
I was having some trouble setting toolchain compatibility with nix flakes environment and noticed the env var the configuration reads is actually different from the one the [documention](https://github.com/cross-rs/cross/blob/51f46f296253d8122c927c5bb933e3c4f27cc317/docs/environment_variables.md?plain=1#L48) and other parts of [code](https://github.com/cross-rs/cross/blob/51f46f296253d8122c927c5bb933e3c4f27cc317/src/rustc.rs#L187) suggests. This fixes the environment variable loaded on configuration
> fix env var for custom toolchain compatibility
